### ISSUE TITLE
warn first when deprecating commands before removing?

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1000]
There's been a couple of diffs to fix issues where we had the wrong name for a command.  I wonder if maybe we could continue to allow users to use the old command but issue a `console.warn`ing and then in the next minor release (since we're still pre-1.0) actually remove the incorrect command.

**Comment by ronkok** [comment]
That's probably wise, although I'm not sure it's worth the trouble for something as obscure as `\utilde` or `\xlongequal`. Perhaps I just wish that to be true because both were my mistakes.

But I am having second thoughts about `\rlap` and `\llap`.  I realize that both are supposed to be functions for text mode, but sometimes they do work in math mode! You can write `\(\rlap{\,/}{=}\)` and it will work fine in AMS-LaTeX. `\rlap` will change text characters to `rm`, but otherwise a text string will also work in `\rlap`. (That's about it for math-mode, though. `\rlap` will mangle a fraction.)

Maybe it would not hurt if KaTeX was more permissive with regard to `\rlap`. Maybe we could have it work like `\mathrlap{\mathrm{#1}}`. That would return text strings and  `\(\rlap{\,/}{=}\)` the same way that LaTeX returns them. And if KaTeX is more permissive with other math than LaTeX, maybe that's not so bad. 

And the extra bonus would be improved backward compatibility with older versions of KaTeX.

**Comment by kevinbarabash** [comment]
Probably best think about deprecation on a case-by-case basis.  As for making KaTeX more permissive than LaTeX, I think that core-KaTeX should strive to emulate LaTeX's behavior as much as possible.  While I think most people using KaTeX to bring existing LaTeX content online, there may be some who are starting out with content they've created in KaTeX and inserting it into a LaTeX document.  For deviations from LaTeX behavior we should try to use macros or contrib.  I think in this case people could use macros if we supported `\ifmmode`, `\else`, and `\fi`.
