### ISSUE TITLE
\begin{align} not support

### ISSUE THREAD

**Issue by nyiuang** [Khan/KaTeX#1007]
I want to use KaTex instead Mathjax, but the existed formula contain \begin{align}, it cannot render with KaTex

**Comment by edemaine** [comment]
You can use `\begin{aligned}` within math mode. Does this suit your purpose?

**Comment by nyiuang** [comment]
@edemaine  the formulas has already exist in database, should I use RegExp to covert align to aligned?

**Comment by edemaine** [comment]
If the formulas are already supposed to be in math mode, then you should be using `aligned` instead of `align`.  Yes, a regex would work.

If you have `\begin{align} ... \end{align}` at the text level, i.e., instead of `\[ ... \]` or something similar, then that is at least correct at the LaTeX level, and you're really looking for a solution to #604. Until that time, a regex replacing `\begin{align}` with `\[\begin{aligned}` and `\end{align}` with `\end{aligned}\]` would work as a stopgap.

**Comment by nyiuang** [comment]
thanks，and one more question: in #604 I see the solution to "align",and are there some other risk of  incompatible formulas grammar between latex and katex ?

**Comment by wookayin** [comment]
Katex renders `aligned` weirdly. To support a compatibility with other grammars (latex), please make `\begin{align}..\end{align}` work.

![image](https://user-images.githubusercontent.com/1009873/64888673-8f780c00-d639-11e9-9c62-d28619d7b906.png)

**Comment by ETOgaosion** [comment]
> Katex renders `aligned` weirdly. To support a compatibility with other grammars (latex), please make `\begin{align}..\end{align}` work.
> 
> e.g.
> 
> ```
> $$
> \begin{aligned}
> V^*(s) &=  \max_a \Big( \underbrace{r(s, a) + \gamma V^*(s')}_{=Q^*(s, a)} \Big)
> \end{aligned}
> $$
> ```
> 
> ![image](https://user-images.githubusercontent.com/1009873/64888673-8f780c00-d639-11e9-9c62-d28619d7b906.png)

It's quite strange, Latex compiler is much smarter, it can right align and left align equation parts seperately, here we can use complex js to achieve this, but I'm lazy, temporarily use left align for all parts.

```css
mstyle {
    width: 100%;
    display: flex;
    flex-direction: row;
    justify-content: left;
}
```
