### ISSUE TITLE
\underline not working with '&'

### ISSUE THREAD

**Issue by aaumar** [Khan/KaTeX#1008]
I have a chemistry equation that need to use underline the whole equation. But I don't get it work when it passes '&' function. any suggestion?

**Comment by edemaine** [comment]
@aaumar Could you provide a complete example of a formula that doesn't work?

**Comment by aaumar** [comment]
here it is
`[%\begin{array}/Cr_2O_7^{-2}+14H^++6e&\rightarrow 2Cr^{3+}+7H_2O &\,|\times 1\\\ \underline{AsO_3^{3-}+H_2O &\rightarrow AsO_4^{3-}+2H^++2e} &\, |\times 3 \\\  Cr_2O_7^{-2}+3AsO_3^{3-}+8H^+&\rightarrow 2Cr^{3+}+3AsO_4^{3-}+4H_2O\end{array}%]`

**Comment by edemaine** [comment]
@aaumar I'm guessing you meant to have arguments on the array, like
```latex
\begin{array}{ll}
/Cr_2O_7^{-2}+14H^++6e&\rightarrow 2Cr^{3+}+7H_2O &\,|\times 1\\\ 
\underline{AsO_3^{3-}+H_2O &\rightarrow AsO_4^{3-}+2H^++2e} &\, |\times 3 \\\
Cr_2O_7^{-2}+3AsO_3^{3-}+8H^+&\rightarrow 2Cr^{3+}+3AsO_4^{3-}+4H_2O
\end{array}
```
This code is invalid LaTeX.  I just checked, and LaTeX gives an error of `! Extra alignment tab`.  Why is complicated (it has to do with the definition of `&`), but this is why it doesn't work in KaTeX too.

I'm guessing you want to underline those two columns (including the space between them, otherwise you could `\underline` the two cells individually).  In LaTeX, you'd probably do this with `\cline`.  Unfortunately, KaTeX doesn't support that yet (#269). Some day I hope...
