### ISSUE TITLE
safe mode (user input mode)

### ISSUE THREAD

**Issue by ctrlcctrlv** [Khan/KaTeX#109]
I don't know what the policy is about LaTeX content posted to UGC sites, whether or not you're patching bugs that deal with this.

However the following TeX was found by my users and they used it to (temporarily) break my site until I filtered \rule:

```
\rule{999em}{999em}
```

I think it should have an upper maximum.

**Comment by kevinb7** [comment]
@ctrlcctrlv Would you be able to create a pull request for this?

**Comment by gagern** [comment]
I actually read the titple “break pages” in terms of paginatin for printed media, not in terms of a defect or unusable web page.

Disabling `\rule` is just a tiny fix. With commands like `\hspace` and `\kern` scheduled for inclusion (#164), one can create excessive amounts of horizontal space, while the `\\` for matrices (#246) can accept an optional argument which can be used to create arbitrary amounts of vertical space. `\begin{pmatrix}a\\[99999em]\end{pmatrix}` could probably cause serious problems for browsers, but we don't want to completely disable custom line skips for `{pmatrix}`.

* So perhaps we want to hack the dimension lexer, to restrict *all* dimensions it parses, at least in safe mode. Anything in excess of `5em` is probably abusive.
* We could also have a look at the vertical extent of the final box, and fail if that exceeds some threshold. Coming up with a reasonable threshold here will be much harder, though, since one might well use `{array}` to display large tables or matrices.
* We could add a counter to keep track of how many spans we're about to place in the DOM, and impose a limit on that, although without looping constructs I can think of no way to achieve this without excessive amounts of input, unless it's using big delimiters which would make it hit the height limit. But perhaps there is a way I haven't considered yet, or perhaps there will be a way when we add more features.
* Finally, we definitely should have a way to disable `\def` and friends once #250 gets resolved.

Should we plan on adding something like `safe:true` to the `options` object passed to `render`? Sould we grant finer control over the various thresholds?

**Comment by ctrlcctrlv** [comment]
I couldn't get KaTeX to work for me and switched to MathJax due to no safe mode (user input mode). I've given up on it.

**Comment by kevinb7** [comment]
@ctrlcctrlv I didn't realize that MathJax has a safe mode.  We'll want to do something similar eventually I just don't know when that will happen.

**Comment by kevinb7** [comment]
http://docs.mathjax.org/en/latest/safe-mode.html
http://docs.mathjax.org/en/latest/options/Safe.html

**Comment by ctrlcctrlv** [comment]
Glad to hear @kevinb7 :) I'll keep watching this ticket as I really did like KaTeX when I was using it.

For my site all contributions are anonymous and even abusive networks like Tor are not blocked, so it's really not an option to "just ban the users" because there are no accounts or karma or anything like that. That's why the commenting system has to be at such a high level of security, and especially all user input processors have to be secure.

Even for slower moving boards where it [may] feasibly be enough to just delete posts of users abusing TeX, only certain people would know how to disable JS to actually get to the posts to delete them. It's also like Reddit where "mods" aren't trained...they're just users who made their own community/got assigned by the creator of a community.

**Comment by jschatz1** [comment]
We are thinking of using your library on our own large site. But are concerned about these security vulnerabilities. What is the status of these?

**Comment by kevinbarabash** [comment]
I looked at the docs for MathJax's safe mode again and it doesn't say anything about MathJax limiting the size or complexity of rendered math.

@jschatz1 thanks for bringing this up as a concern again.

**Comment by DouweM** [comment]
@kevinbarabash Does KaTeX have any of the avenues for XSS issues that MathJax apparently has, which their Safe mode guards against?

**Comment by kevinbarabash** [comment]
@DouweM we don't have any extensions for embedding links or arbitrary markup.

**Comment by DouweM** [comment]
@kevinbarabash All right, I'm happy to hear that. Then the main issue for us seems to be https://github.com/Khan/KaTeX/issues/158, which could be worked around by using web workers :)

Thanks for your quick responses!
