### ISSUE TITLE
\ge and \gt looks not in the same baseline

### ISSUE THREAD

**Issue by FavorMylikes** [Khan/KaTeX#1149]
$$l_i(x)=\prod_{j=0,n\ge i\gt j\ge 0}^n\frac{(x-x_j)}{(x_i-x_j)}$$
    $$L=\prod_{i=0,i\not = j}^ny_i\frac{(x-x_j)}{(x_i-x_j)}$$
    $$n\ge i\gt j\ge 0\geqslant1$$

**Comment by FavorMylikes** [comment]
![lcl2n _ a j57ly_00nuc c](https://user-images.githubusercontent.com/16064851/35981472-4c4f0fb8-0d28-11e8-986d-928455d18bb9.png)

**Comment by kevinbarabash** [comment]
This is standard TeX behavior.  Here's a rendering from quicklatex.com:

<img width="679" alt="screen shot 2018-02-08 at 5 11 50 pm" src="https://user-images.githubusercontent.com/1044413/36001099-301f0044-0cf3-11e8-9592-0b038604d275.png">

**Comment by kevinbarabash** [comment]
@FavorMylikes since this appears to be the default behavior of LaTeX I'm going to close this.  If you would like adjust the height of `<` and `>` I would try defining a macros to redefine `\lt` and `\gt`.  Probably best to give those macros different names though as I don't believe our macro system provides a way to safely redefine a command using that command yet.  See https://github.com/Khan/KaTeX#rendering-options for details on using macros.

**Comment by FavorMylikes** [comment]
Thank you for your reply and suggest, I will try it.
