### ISSUE TITLE
Parse error when parsing HTML special characters

### ISSUE THREAD

**Issue by selipso** [Khan/KaTeX#1185]
When using the `katex.renderToString()` method on f&#39;(2)=g&#39;(2)=3 I get the following error:

```
f&#39;(2)=g&#39;(2)=3 
ParseError: KaTeX parse error: Expected 'EOF', got '&' at position 3:  f&̲#39;(2)=g&#39;(…
```
In a regular HTML page, the above would render f'(2) = g'(2) = 3

Is there a flag that allows pass-through for HTML special characters on the server-side? I'm running this script using node.js. 

More of an aside, but I've noticed I also get parsing errors when trying to parse regular HTML with delimiters $$ and \( \). Are there plans to support server-side HTML conversion with the standard mathjax delimiters? Thanks for your great work so far on this library.

**Comment by ylemkimon** [comment]
You can use `_.unescape` from `loadash` or packages like `unescape`.

**Comment by edemaine** [comment]
Right, if you want to unescape HTML before calling `renderToString` explicitly, you should do something like
```js
katex.renderToString(_.unescape(x))
```
We can't do this automatically for you, because
```latex
f&#39;(2)=g&#39;(2)=3
```
has a meaning in LaTeX (though admittedly it's a weird one, involving a macro with 39 arguments that appears in a tabular environment).

How are your `'` characters getting escaped in the first place?

**Comment by selipso** [comment]
Ah ok, makes sense, thanks. The mixed HTML/LaTeX content comes from an effort to unify different equation formats (including MathML :( ) to look consistent with each other. MathJax worked well for a while, but it's inevitable that native HTML/CSS is more cross-platform and scalable.

**Comment by edemaine** [comment]
Cool. Sounds like a challenge!
