### ISSUE TITLE
Symbol aliases

### ISSUE THREAD

**Issue by jmeas** [Khan/KaTeX#122]
Some symbols have aliases, like `\wedge` and `\land`. From what I can see KaTeX doesn't support these aliases. There are at least two options to support this functionality:
1. Add a new property on each symbol for alias(es)
2. Add duplicate symbols

Thoughts?

**Comment by kevinbarabash** [comment]
I believe this has been addressed in a couple of ways.  #128 included some aliases and there have been a number of PRs since then that included other aliases.  We also now support `defineMacro` which can be used defined aliases although most (all?) of the existing symbol aliases use `defineSymbol` b/c it's already pretty short to write.
