### ISSUE TITLE
not support some mathjax syntax

### ISSUE THREAD

**Issue by henryatman** [Khan/KaTeX#1231]
for example:

```
\begin{align}f'(3) &=\lim_{h \to 0}{(3+h)^2 - 3^2\over{h}} \\
&=\lim_{h \to 0}{9 + 6h + h^2 - 9\over{h}} \\
&=\lim_{h \to 0}{6h + h^2\over{h}} \\
&=\lim_{h \to 0} (6 + h) \\
&= 6.
\end{align}
```

```
\begin{align}
\ [1, 3, -5] \cdot [4, -2, -1] &= (1)(4) + (3)(-2) + (-5)(-1) \\
&= 4 - 6 + 5 \\
&= 3
\end{align}
```

it works very well in mathjax, but katex not work, 

even katex in most time work very fast ,but not support all syntax is very annoy，

can't support this ? thanks

**Comment by ronkok** [comment]
@henryatman If you change `{align}` to `{aligned}` in your expression, it will work fine.

In LaTeX, `{align}` works is if is placed into a text mode section of the LaTeX document. `{aligned}` works if one is already in math mode. Since KaTeX is in math mode to begin with, `{aligned}` is the proper environment.

**Comment by henryatman** [comment]
@ronkok , it is work, wonderful, very thank you help and reply,
