### ISSUE TITLE
\llap is misaligned after \frac

### ISSUE THREAD

**Issue by spontaliku-softaria** [Khan/KaTeX#1234]
\frac{1}{2}\llap| in Katex renders
![screenshot_20180321_140526](https://user-images.githubusercontent.com/6647438/37697707-ecccda62-2d10-11e8-9ce9-3f8e08ad8de0.png)

However in Mathjax it renders
![screenshot_20180321_140453](https://user-images.githubusercontent.com/6647438/37697693-d6dbd9ba-2d10-11e8-8ce7-f886a3c36eef.png)

**Comment by edemaine** [comment]
I confirmed that center alignment is what's supposed to happen (i.e. what happens in LaTeX).

I observe that adding a rule to `.llap .inner` of `top: 0` fixes the problem in all examples I've tried.  But I'm not an expert in `position: absolute`.  Can anyone confirm that this is what we ought to do?

Some other bugs I encountered while testing (but none too important):
* In LaTeX, `|` renders as a horizontal bar in text mode (including in `\llap`).  Confusing...  Not sure we want to implement this, but probably should at least in `strict` mode.
* On the KaTeX demo page, `\llap{$|$}` fails with error message `Cannot read property 'fontName' of undefined`.  This seems to have been fixed in master though, perhaps by #1213.

**Comment by ronkok** [comment]
PR #1162 fixes this problem. It isn't merged into master yet.

![fraclap](https://user-images.githubusercontent.com/16403058/37728750-536362be-2cf8-11e8-9c59-5f804de8b61b.PNG)

**Comment by spontaliku-softaria** [comment]
@ronkok I've tried brach with your PR. It is fixed indeed, but it introduces angother change - distance to left symbol is changed.
For example `\sin\llap|1` from khan.github.io/KaTeX:
![screenshot_20180322_182900](https://user-images.githubusercontent.com/6647438/37768424-2170114a-2e00-11e8-9bef-9d98eb82c2fd.png)
And the same in your brach (if I built it correctly):
![screenshot_20180322_182913](https://user-images.githubusercontent.com/6647438/37768425-25efd2b4-2e00-11e8-8106-75beb543cda7.png)
I don't know which one is correct, just noticing.

I believe second breaks usage of lap with `|` as a cursor (it was mentioned in some issue) because distance between symbols change while cursor is moving.

**Comment by ronkok** [comment]
Well, that's disappointing. Obviously my PR needs some work. I'll try to get it working before the next KaTeX release.

**Comment by ronkok** [comment]
@spontaliku-softaria I've pushed a commit to PR #1162 that fixes the issue you found with horizontal alignment relative to an adjacent span.  Your example now renders as:

![lapmord](https://user-images.githubusercontent.com/16403058/38005574-193c7046-31f6-11e8-9145-bd64d1332562.PNG)

**Comment by spontaliku-softaria** [comment]
@ronkok thanks, now it works right in most places. But I stepped on another case where it looks wrong - `\sqrt{\mathclap|a\mathclap|}\mathclap|` :disappointed:. Here is your branch:
![screenshot_20180330_144046](https://user-images.githubusercontent.com/6647438/38129229-5b243316-3428-11e8-9616-3834e675d3b6.png)
Here is original:
![screenshot_20180330_144117](https://user-images.githubusercontent.com/6647438/38129238-6abbd98c-3428-11e8-89a0-fb1f219b1f7f.png)
In particular, looks like it is last `\mathclap|` who is misaligned - it overlaps `a` while being outside of `\sqrt\`. Adding another symbol in the end fixes it:
![screenshot_20180330_144259](https://user-images.githubusercontent.com/6647438/38129294-a727e42e-3428-11e8-9782-5ff18b45aa87.png)

**Comment by ronkok** [comment]
I'm out of ideas. If anyone wants to take on this little Chrome nuance, feel free.

**Comment by edemaine** [comment]
Fixed in #1162
