### ISSUE TITLE
Symbols – delimiter 'duplicates' in Mathjax

### ISSUE THREAD

**Issue by jmeas** [Khan/KaTeX#128]
In three cases, Mathjax creates a different output for a given input when the symbol is used as a delimiter.

These three cases are, `\lt`, `\gt` and `\backslash`.

Like KaTeX, Mathjax uses the input as the property keys in its objects. It handles these duplicate entry by having multiple objects for different categories, and also with what might be an inconsistent naming schene. Delimiters, for instance, [are in their own object](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js#L675) and have a `\\` prefix whereas the other entries don't.

Here's a chart of the inputs and outputs

| Input | Delimiter Output | 'Regular' Output |
| --- | --- | --- |
| `\lt` | ⟨ | < |
| `\gt` | ⟩ | > |
| `\backslash` | \ | ∖ |

This issue is to discuss how we should handle this in KaTeX. I suppose some options are to just select one to use in all contexts, to not allow these inputs as delimiters, or to make changes to the way symbols are stored to allow this distinction.

**Comment by kevinbarabash** [comment]
Given `\left< \frac{1}{x} < \frac{1}{y} \right>` both LaTeX and KaTeX produce the same output.  Since `\lt` and `\gt` are aliases to `<` and `>` I would expect KaTeX to produce the same output for `\left\lt \frac{1}{x} < \frac{1}{y} \right\gt` which it does.

KaTeX:
<img width="107" alt="screen shot 2017-09-17 at 12 31 31 pm" src="https://user-images.githubusercontent.com/1044413/30522858-e4377dc4-9ba4-11e7-8087-cc4e8651274f.png">

LaTeX:
<img width="191" alt="screen shot 2017-09-17 at 12 38 59 pm" src="https://user-images.githubusercontent.com/1044413/30522882-3777c444-9ba5-11e7-976d-9b3c6f5fc72f.png">

The `\backslash` behavior differs from MathJax but matches LaTeX which is what we want.

KaTeX:
<img width="123" alt="screen shot 2017-09-17 at 12 36 09 pm" src="https://user-images.githubusercontent.com/1044413/30522846-d456ea98-9ba4-11e7-947e-d582a46334c5.png">

LaTeX:
<img width="198" alt="screen shot 2017-09-17 at 12 38 56 pm" src="https://user-images.githubusercontent.com/1044413/30522884-3ec06b7a-9ba5-11e7-8f59-cb2959eb2e8f.png">
