### ISSUE TITLE
0.10.x release planning

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#1311]
There's recently been a number of fairly substantial new features and changes merged into `master`.  I feel like it's probably worth moving to `0.10.x`.  Also, correct me if I'm wrong, the changes to the settings/options to use `strict` feels like a breaking change.

**Comment by edemaine** [comment]
Assuming we default `strict` to `"warn"`, there might be some now warnings for users.

But the bigger change is line breaks. This will definitely cause different behavior for inline math (hopefully for the better). So 0.10 sounds good to me.

I'd suggest we go through a series of alphas and/or betas, like 0.9, given the number of changes.

**Comment by kevinbarabash** [comment]
I think we should default `strict` to `"ignore"`.

> But the bigger change is line breaks. 

Good call.

> I'd suggest we go through a series of alphas and/or betas, like 0.9, given the number of changes.

Hopefully we won't need as many alphas/betas as last time.

**Comment by edemaine** [comment]
Haha, hopefully!

Oh, also the new throwOnError behavior is changed (and hopefully much harder to accidentally code injection vulnerabilities).

**Comment by ylemkimon** [comment]
How about a major version release, i.e., v1.0? Do we have milestones for 1.0?

**Comment by edemaine** [comment]
v1.0 is a sign that the software is ready for production use.  I personally think KaTeX has reached that level, though I'm sure some disagree (doesn't support all MathJax features).  If we'd rather make milestones for 1.0 and then achieve them, though, we can stick with 0.10 for this bursting release.

By the way, I've mentioned before but it bares repeating in this thread: I think it'd be good for #1278 to land before 0.10.0 gets released, at least the final version, but ideally even the alpha version, so that users don't need to learn about `unicodeTextInMathMode`.

**Comment by ronkok** [comment]
A release would also benefit from #1162.

**Comment by kevinbarabash** [comment]
I think making a milestone for 1.0 is a good idea.  That way we can go through all of our existing issues and pending PRs to see if there's anything that we think should be addressed before moving to 1.0.

**Comment by kevinbarabash** [comment]
0.10.x has had it's first -alpha so I think it's safe to close this.  @ronkok I'll publish another alpha (or beta) when #1162 is ready.
