### ISSUE TITLE
Improve release script

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#1428]
We should consider adding the following features to the release script:
1. Update `gh-pages` branch's `index.html` to new version. (mentioned in #1424)
2. Update `README`s even when using 1-argument form. (mentioned in #1423)

As a side note, this will only work for people who can directly push to the repo.  I think this should include all NPM package maintainers, but it currently doesn't include me.  Is there a way to only make this possible with an extra argument to `git push`, so that it cannot (easily) be done accidentally, except from the release script?

**Comment by kevinbarabash** [comment]
@edemaine you should be able to push directly even to `master`.

w.r.t. `gh-pages` we should look at other ways of handling documentation.  I'd rather have it one the main branch in the docs folder.

We might also look at hosting the site on netlify and then using a static redirect.  netlify also can serve all previous versions which would come in handy when providing versioned documentation.

**Comment by ylemkimon** [comment]
With required status checks and/or required pull request reviews enabled, commits cannot be directly pushed to the master, without a pull request. And I think this should be the right behavior, since it's the _master_ branch.

I think release workflow should involve at least two people, e.g.:

1. One runs the release script, which creates a branch, and opens a pull request
2. Another reviews the pull request, approves it, and merges it
3. CI deploys package to the NPM

**Comment by kevinbarabash** [comment]
I didn't realize that.  I guess the reason why I was able to run the script as is is b/c I'm an admin.  I'm glad we're talking about this.  Having non-admins be able to deploy is important.

@ylemkimon your plan looks good.  I'm not sure how to do step 3 though.

**Comment by rrandallcainc** [comment]
I'm assuming CI can not just push a tag without some sort of user intervention, right? If we're following semver rules, someone would need to specify major/minor/patch bump. Unless I'm misunderstanding.

**Comment by edemaine** [comment]
I think the idea is that the release script would still push a developer-specified tag (including version number), but that CI would do the `npm publish`.  I'm not sure that's really that important.  The big thing would be to move to a PR model instead of directly touching master as the script currently does.

**Comment by ylemkimon** [comment]
#1 will be easy now, as we have website on the `master` branch 😄

**Comment by kevinbarabash** [comment]
> The current release script seems to support releasing from another branch. I've added detailed instructions in #1521.

I think I'll give that a try when I do the release this weekend.  @ylemkimon thanks for adding that option.  Also, I'm happy to see that updating the docs are part of the publish workflow.  I'm a little scared/excited about versioned docs though.  Nothing ventured nothing gained I guess.

**Comment by edemaine** [comment]
Same here. It would be cool if you use the new PR approach because then we can double check that the publish script os checking in the right things. Maybe don't even need to use the beta moniker in that case, as we probably won't need to change the NPM release if something goes wrong, only the PR.

**Comment by ylemkimon** [comment]
#1511 still pushes the tag and publishes to the NPM(`yarn publish`) and to the GitHub pages(`yarn publish-gh-pages`), even running on another branch.

**Comment by edemaine** [comment]
Thanks for catching this! I assume it's just the publish-gh-pages that is incorrect?

**Comment by ylemkimon** [comment]
@edemaine If we're moving to a PR model, it'd be preferable to push the tag and publish to NPM and GitHub pages after the PR gets accepted and merged. I think we can do this automatically using CI or manually using a flag.

**Comment by edemaine** [comment]
@ylemkimon Maybe for starters we can just separate the two processes, and run both of them manually?  Then we can automatic the NPM part if we want (though it's also not hard to run it manually).

But I'm unclear how we're supposed to test the documentation before we release to NPM, unless/until we have something like #1520.

**Comment by mbourne** [comment]
Some libraries with versioned docs provide a problem for the searcher, as follows. 

An early release of the documentation gets a lot of links pointing to it (perhaps there was a popular change, or something), then the search engines prioritise that version of the docs because more links point to it. Then a user comes along searching for something, lands on old documentation, and can't understand why the suggested code does not work in their latest version. (Happened to me way too often...)

This may already be in the plan, but can I suggest something like the following:

Latest documentation: `katex/documentation/blah...`

All previous documentation: 
`katex/v0.9.1/documentation/blah...`
`katex/v0.9.2/documentation/blah...`
etc

This way, the current documentation will get growing numbers of links over time, and most of the previous ones will get very few, eventually falling into oblivion.

**Comment by ylemkimon** [comment]
@mbourne Latest release (stable) version documentation will be available at https://khan.github.io/KaTeX/docs/ and previous version, v0.9.0 for example, documentation will be available at https://khan.github.io/KaTeX/docs/0.9.0/. And if we decide to publish `master` documentation, they will be available at https://khan.github.io/KaTeX/docs/next/.

**Comment by mbourne** [comment]
@ylemkimon Looks perfect!

**Comment by ylemkimon** [comment]
- [ ] CHANGELOG
- [ ] Add check to the CI whether SRI has been changed
