### ISSUE TITLE
How to make the equations appear inline with the text?

### ISSUE THREAD

**Issue by edigleyalexandre** [Khan/KaTeX#1481]
It would be interesting that the mathematical symbologies appeared also aligned with the text, as I do in my blog. How to make this change?

**Comment by edemaine** [comment]
We'll need more information about how you're using KaTeX, or a link to the site. In general, KaTeX provides mechanisms for inline math (aa you desire) and display math. By default, `\(...\)` should give you inline math, but the dedaults may have been changed in your environment.

**Comment by kevinbarabash** [comment]
@edigleyalexandre can you link to the blog that isn't working?

**Comment by edigleyalexandre** [comment]
I'm running Katex on a test blog at this [link](https://alunos.prof-edigleyalexandre.com/2018/07/testando-o-interpretador-katex.html).

**Comment by ronkok** [comment]
@edigleyalexandre That page is running KaTeX release 0.7.1. The current release is 0.10.0-beta and a lot has been added since 0.7.1, as is described on the [release page](https://github.com/khan/katex/releases).

If you have any control of what is in each page's `<head>`, you want to change the KaTeX references to the ones listed [here](https://github.com/Khan/KaTeX/tree/master/contrib/auto-render#usage).

**Comment by kevinbarabash** [comment]
@edigleyalexandre it looks https://alunos.prof-edigleyalexandre.com/2018/07/testando-o-interpretador-katex.html is working.  Which one isn't working?

**Comment by edigleyalexandre** [comment]
In my [main blog](https://www.prof-edigleyalexandre.com/2018/07/regra-escrever-numero-composto-como-soma-de-dois-quadrados-inteiros-positivos.html) I'm using Mathjax. With Katex, commands are not rendered.

**Comment by edigleyalexandre** [comment]
When I upgraded to version 10 it worked normally on all blogs. Now you just need to switch to a more stylish source. Has as?

**Comment by edigleyalexandre** [comment]
When I upgraded to version 10 it worked normally on all blogs. Now you just need to switch to a more stylish source. Has as?

Using the environment \ begin {equation *} does not render.

**Comment by ronkok** [comment]
> \ begin {equation *} does not render.

We haven't supported that particular environment yet. Check the [function support page](https://khan.github.io/KaTeX/function-support.html). You can probably find something that meets your needs.

**Comment by edigleyalexandre** [comment]
> We haven't supported that particular environment yet

Ah! \ begin {equation *} would be just one more.

**Comment by edigleyalexandre** [comment]
@ronkok How do I recommend a suggestion for Katex in order to implement the specific environment for: **\begin {equation *}**? It would be too useful for many blogs.

**Comment by ronkok** [comment]
@edigleyalexandre 

That request already exists in issue #445, and is reinforced by the request for the `{split}` environment in issue #1345. I'm sure we'll get to it eventually. I don't want to promise any dates.

**Comment by edemaine** [comment]
@edigleyalexandre Is there a particular reason you prefer `\begin{equation*}` over `\[` or `$$`?  I've written in #445 how you can enter math mode via custom begin/end commands.  See https://github.com/Khan/KaTeX/issues/445#issuecomment-406284568

**Comment by edemaine** [comment]
Moving discussion back over here, as this has nothing to do with `{equation}`.

I had no trouble adapting your example to run in KaTeX.  See https://codepen.io/edemaine/pen/GBNEeN

**Comment by ronkok** [comment]
> I added as indicated, but it does not render.

I'm also confused. When you say that "it" does not render, do you mean that 

1. something between `$...$` delimiters does not render? , or
2. the `{equation}` environment does not render?

If "it" is something between `$...$` delimiters, please indicate the specific item, because what I see does render.

If "it" is the`{equation}` environment, well, yes, that one isn't supported yet.

**Comment by ronkok** [comment]
>  translating from English to Portuguese

That's not a problem at all. We just have to be a little patient with each other. Sometimes I have to ask for a clarification.

Now regarding `{bmatrix}`, `{cases}` and `{gather}`, they should all render in KaTeX. The difference is that the KaTeX auto-render plug-in does not recognize environments as something that should automatically put you into KaTeX math mode. So in your document, you should try `$$\begin{bmatrix}...\end{bmatrix}$$` and that should work fine. That's different from MathJax, which does not need the `$$` in order to render an environment.

The `{equation}` environment is not supported in KaTeX, but I usually find that `{aligned}` or `{alignedat}` will do what I need.

**Comment by edigleyalexandre** [comment]
@ronkok You believe these environments will be implemented in the future. If so, I'd rather wait for the new versions. Once again thank you for your patience. This is admirable today.

**Comment by ronkok** [comment]
I believe it is appropriate to close this issue. The overall rendering problem has been overcome. Support for the `{equation}` environment is a duplicate to an existing issue.
