### ISSUE TITLE
not equal sign sometimes renders incorrectly

### ISSUE THREAD

**Issue by HosseinAgha** [Khan/KaTeX#1491]
This formula is interesting as it shows the case with a correct render and wrong render at the same time:

```\begin{aligned} & { z(z-2) \ne 0 } \Rightarrow \left\{ \begin{matrix} z\ne 0 \\ z\ne 2 \\ \end{matrix} \right. \end{aligned}```

![image](https://user-images.githubusercontent.com/12998499/42905312-e5398a7c-8aec-11e8-8d3e-f095cd050ff9.png)

I used the KaTeX's github.io renderer for the image.

Looks like it has something to do with the height of the matrix as it will be fixed by removing it.   
We can fix it by bringing `matrix` out of the `aligned` environment but it also causes the `rightarrow` and the `{` to get unaligned as it is not really a correct LaTeX formula.  

![image](https://user-images.githubusercontent.com/12998499/42905763-3cad98ec-8aee-11e8-93b1-8d9eae77373e.png)

Version: 0.10.0-beta

**Comment by ronkok** [comment]
Well, we assign `style="position: absolute;` to the solidus, U+0338. [[ref]](https://github.com/Khan/KaTeX/blob/master/src/buildHTML.js#L186) Then the trouble occurs when it is placed in a line where the HTML bounding box is taller than 1 em. Because it's `position: absolute`, it's no longer attached to the baseline. Instead, the top of the character is attached to the top of the bounding box.

When faced with a similar situation in `\mathrlap`, I put the offending fragment in a `vlist` with offset zero. It seems like there should be a more elegant way to prevent this from happening, but nothing else occurred to me and the `vlist` works.

**Comment by ronkok** [comment]
I wonder why KaTeX uses a macro to define `\ne` when it could have been more easily defined in `symbols.js`. There is a perfectly good glyph available in KaTeX_Main-Regular.

**Comment by edemaine** [comment]
@kevinbarabash This looks like a bug in `\not`.  Related to #1267, which we never merged.  Perhaps that PR solves it?  (But it has an outstanding issue, at least on the font side, though I think those glyphs could now be removed.)  I'm also left wondering why `\not` can't be handled like the other accents, which don't have this issue.

@ronkok `\ne` became a macro in #1400.  Partly this is because the glyphs for `\ne` and `\notin` are currently messed up -- see https://github.com/KaTeX/katex-fonts/issues/47 -- so instead of maintaining them, we moved to the way LaTeX does it.
