### ISSUE TITLE
Single line comment error

### ISSUE THREAD

**Issue by ronkok** [Khan/KaTeX#1506]
`\[ x = 1 % comment \]` results in an error. The error goes away if a linefeed is placed after the comment.

![comment](https://user-images.githubusercontent.com/16403058/43331498-e9333c56-917a-11e8-93ac-e3cd6b4327ab.PNG)

**Comment by edemaine** [comment]
I believe this was an intentional; see the discussion in #884.  The motivation is that `\[ x = 1 % comment \]` would also not work in LaTeX, whereas the following does work in LaTeX:
```latex
\[ x = 1 % comment
\]
```

I agree that this could use better documentation and error messages, though.

**Comment by ronkok** [comment]
Well it does work in MathJax, and besides it is the straightforward behavior, so why not have it work in `strict: false` mode?  

In `strict: warn` mode, let single line comments work and write a console message that tells people it can't be copied verbatim to LaTeX.

**Comment by edemaine** [comment]
@ronkok That seems like a good idea.  It might be a bit tricky to implement because it's a change at the lexer level, but should be possible...

**Comment by edemaine** [comment]
This has turned up a bug in `\href`: `\href{x%y}{hi}` works fine if it's a single line, but a multiline input like
```latex
\href{x%y}{hi}
bye
```
causes the comment behavior to trigger, resulting in an unclosed `{`.  LaTeX doesn't work this way, because `\href` redefines how `%` works.  I think we'll need to fix this in the same way that `\verb` works.
