### ISSUE TITLE
Arial Support

### ISSUE THREAD

**Issue by fsonmezay** [Khan/KaTeX#1702]
Is ther e a plan to add Arial Font support for Katex -?

**Comment by ronkok** [comment]
@fsonmezay I do not expect that KaTeX will support Arial font.

One of the reasons that KaTeX is fast is that it does not have to query the browser for dimensions of font glyphs and then wait for the browser to reply. KaTeX has detailed metrics for the glyphs in the KaTeX font, so it can work with those metrics. In order to use another font, one would have to first extract the metrics for each glyph in the font and make that data available to KaTeX. 

That might happen some day for one of the mathematical fonts, but I don't think it is likely to happen any time soon for Arial.

**Comment by edemaine** [comment]
@fsonmezay If you're looking for a sans-serif font, you *can* use `\mathsf{example}` or `\textsf{example}`. This uses the sans-serif font in the Computer Modern typeface.

**Comment by fsonmezay** [comment]
@ronkok , @edemaine Thank you both for your time and detailed explanations.

@edemaine we already use `\sf` for the formulas, but in some cases we thought we can use Arial font.
