### ISSUE TITLE
MathJax not defined

### ISSUE THREAD

**Issue by HeinrichHartmann** [Khan/KaTeX#192]
![image](https://cloud.githubusercontent.com/assets/2446981/6442915/b4a419fc-c0f3-11e4-9c3d-1737f42f7bf3.png)

**Comment by HeinrichHartmann** [comment]
Found on https://jsperf.com/katex-vs-mathjax

**Comment by xymostech** [comment]
I think this is because that test uses raw `http://` links to the MathJax script, but the page you're loading uses `https://`. I recently made a newer test that uses `//` links (so they automatically use whatever protocol you're using) at https://jsperf.com/katex-vs-mathjax/34 that should work. I'll be releasing a newer test soon that should use the current version of KaTeX.

**Comment by HeinrichHartmann** [comment]
Confirmed. Same link with http:// works.

**Comment by HeinrichHartmann** [comment]
New link over https:// has other issues:
![image](https://cloud.githubusercontent.com/assets/2446981/6455681/893a4f0c-c157-11e4-859f-239647f63910.png)
http:// works again, fine.
