### ISSUE TITLE
\LaTeX not rendered

### ISSUE THREAD

**Issue by rgbkrk** [Khan/KaTeX#224]
``` latex
\KaTeX
```

renders just fine but

``` latex
\LaTeX
```

doesn't. I'm all for letting `\KaTeX` be rendered, but there are plenty of times people want to render `\LaTeX`.

**Comment by xymostech** [comment]
There was a pull request to add this: #131. I'd like for `\LaTeX` to be rendered using the true offsets/dimensions as in actual LaTeX, which is why it wasn't merged in. This is something that would probably be nicer if this was just implemented as a macro whenever we figure that out, but if you (or anyone else) wants to try to incorporate the true metrics.

**Comment by gagern** [comment]
A non-macro definition on the other hand should be fairly easy. I've written some details about that in the pull request. Read that first to better understand the macro in question.

Doing this as a macro following the official definition would be really tricky, since we'd need kerning (which might be a good thing to have in any case, and which shouldn't be too hard except for the strange lexing rules for lengths), and we'd need box registers and ways to measure the content of boxes at least vertically (I believe horizontally is impossible), and we'd need raw box construction commands like `\vbox to …`, and we'd need flexible glue for `\vss`. I don't think this is realistic in the near future, even though I've recently made some progress regarding macro definitions.

The logo could probably also be described as a macro using simpler means, like e.g. `\raisebox` instead of the `\vbox`. But that would mean manually computing the offset up front, and hardcoding it into the macro instead of deriving it from the font metrics. I'm not sure this is desirable, particularly seeing how many people (myself included) have asked for KaTeX to also work with different fonts.

**Comment by kevinb7** [comment]
We should try to add ```\kern``` b/c it's used in quite a few different commands.

**Comment by kevinb7** [comment]
I added ```\kern``` to the list of missing horizontal spacing commands in https://github.com/Khan/KaTeX/issues/164.

**Comment by edemaine** [comment]
Fixed by #974 (thanks to previous additions of `\kern` and `\raisebox`).
