### ISSUE TITLE
Can use without special fonts?

### ISSUE THREAD

**Issue by bguiz** [Khan/KaTeX#231]
- KaTex uses these font files: https://github.com/Khan/KaTeX/tree/master/static/fonts
- Is it possible to make KaTex work with standard fonts?

**Comment by spicyj** [comment]
Not really, since KaTeX relies on knowing the font metrics in order to position things accurately. See also #123. Possibly we could make a mode that looks okay on some common pre-installed fonts though without requiring font data.

**Comment by bguiz** [comment]
> Possibly we could make a mode that looks okay on some common
pre-installed fonts though without requiring font data.

Yes please - this is exactly what I am after! One that would work with one
out of the default set of fonts commonly available in browsers would be
perfect.



W: http://bguiz.com

**Comment by kevinb7** [comment]
I think this is going to be difficult because some of the symbols don't exist in the fonts that come with most browsers.  Also, even though browsers support a common set of fonts like Arial, Times New Roman, Courier, etc. the metrics can actually differ between operating systems, e.g. Courier on iOS is quite a bit wider than Courier on other systems.  I'm sure there are other more subtle instances of this.  Lastly, if a particular glyph doesn't exist in one font then some operating systems will substitute it from another font which will have different metrics.

I'm going to close this for now.  @bguiz what's the use case for using common fonts?  Maybe we can look at the problem from a different angle.

**Comment by spicyj** [comment]
We don't use widths at all in KaTeX's calculations. We should certainly be able to produce output that looks as good as using `<sup>` tags, etc. without any custom fonts, though square roots and large delimiters would be harder.

**Comment by kevinb7** [comment]
> We don't use widths at all in KaTeX's calculations.

I made that realization at one point and then forgot.  Thanks for reminding me.
