### ISSUE TITLE
A CDN pointing to the latest "release"

### ISSUE THREAD

**Issue by PeterBocan** [Khan/KaTeX#239]
I have one little enhancement on KaTeX - what about adding/setting the CDN to point to the latest release?

**Comment by spicyj** [comment]
This would have to be fixed in cdnjs.com; they've got an issue here already: https://github.com/cdnjs/cdnjs/issues/360.

In general I wouldn't recommend always upgrading automatically to new major versions because we might have breaking changes, either in the TeX syntax supported or in the JS API. :)

**Comment by PeterBocan** [comment]
Ah, I see, that's sad. :D

**Comment by jimaek** [comment]
jsDelivr supports latest links and version aliasing if you are interested. 
Example http://cdn.jsdelivr.net/katex/latest/katex.min.js
http://cdn.jsdelivr.net/katex/0.3/katex.min.js (latest 0.3.x)

More info https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/

**Comment by PeterBocan** [comment]
@jimaek that's amazing!
