### ISSUE TITLE
Automate screenshotter on travis-ci

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#300]
https://github.com/moul/travis-docker allows you to run docker on travis-ci.  We can use it to automate the screenshotter so that it runs on every commit and fails the build if there differences in the images.

Depends on: https://github.com/Khan/KaTeX/pull/264

**Comment by gagern** [comment]
Note that

1. Travis itself is [moving to Docker](http://docs.travis-ci.com/user/migrating-from-legacy/), offering lots of benefits, speed in particular.
2. Currently, there is no sudo support within their containers, for security reasons.
3. travis-docker makes excessive use of sudo, and in particular runs its whole user-mode linux with sudo. So it can't run on the new infrastructure, which is why some of the examples state `sudo: true`.

This raises several questions.

* Does the fact that they themselves use Docker help us somehow? I've just posted a request (https://github.com/travis-ci/travis-ci/issues/4266) for linking with Selenium containers, let's see how that turns out.
* Does the move towards Docker mean that the old system will get deprecated any time soon? If so, we shouldn't build on some technique which won't work on the new setup.
* Will they get sudo support enabled on the new infrastructure eventually? I know too little to tell, and haven't yet found any public discussion of this issue. Chances are the old infrastructure will stay around while that support is still missing, but I'm not sure of this.
* Will travis-docker ever work without requiring sudo? That depends on whether UML can be made to run without root privileges. I'll have to test that.

I believe that it *should* be enough to take all the packages used inside the docker, package them in some tarball, and use that in combination with `LD_LIBRARY_PATH` to run the screenshotter as a normal user with no special privileges or additional virtualization layers. The main benefit would be speed, since the container would be ready for use more quickly. The main drawback would be that we'd have two different ways of running the screenshotter (btw, shouldn't this be screenshooter?), which I know you don't like.

**Comment by kevinb7** [comment]
If we're using the same packages then we should get the same results.  It might make the tests longer to run if a whole bunch of separate packages have to be installed.    Is there an easy way to get the list of packages from the docker images?  Would we be able to run both the Firefox and Chrome tests in one travis-ci job using `LD_LIBRARY_PATH`?

`travis-docker` seems pretty easy to get up and running so it might be worth spending a little bit of time investigating that.  If it looks like it's going to take lots of time then we should look at other options.

**Comment by gagern** [comment]
See https://github.com/gagern/selenium-chroot for my own idea of how to handle the situation. Although I must confess that it turns out to be more problematic than I had envisioned, so it doens't work yet. It would still be great if this could be made to work.

**Comment by gagern** [comment]
Look what I found today: http://docs.travis-ci.com/user/docker/

It looks as if Travis now supports docker usage all by itself. That should simplify things quite a lot! I'll try to make this work for KaTeX as soon as I find the time, unless someone else did so by then.

**Comment by kevinbarabash** [comment]
Nice find.
