### ISSUE TITLE
Chrome screenshots have diverged from a recent commit

### ISSUE THREAD

**Issue by kevinb7** [Khan/KaTeX#325]
I disabled Chrome screenshots in https://github.com/Khan/KaTeX/commit/0dc9eed1c42ab111b1ba1d795270e579d4b423cc.  If someone else could locally re-enable Chrome screenshots and re-generate them to see if they're seeing differences that would be much appreciated.  I will try to do the same and post images in a branch this weekend.

**Comment by gagern** [comment]
The title is incorrect: at least for me, chrome screenshots have *not* diverged from the *initial* commt, or at least not all of them. However, the *have* diverged from the most recent commit, namely ce99abd1f209b49680910fb9a93a7a45c0025f25. That commit by @xymostech needs some investigation. Taking `Arrays-chrome.png` as an example, I can reproduce the state from b7e1581869ea4f5d20a6b7d7f0b0dc7bb4ae6f64 but not from ce99abd1f209b49680910fb9a93a7a45c0025f25. The PNG files from these two commits are the same in terms of pixel values (i.e. `pngtopam` yields the same result), but not in terms of binary encoding. Surprisingly, the differences are not in metadata, nor in the compression efficiency. The files have exactly the same size, the individual `IDAT` chunks have equal size, but still the pixels are encoded somewhat differently.

Unless @xymostech or someone else has some idea as to *why* the image got encoded differently, my best bet would be addressing the symptom by parsing and then recompressing the PNG file. One way would be using some JavaScript-based PNG encoder/decoder. [pngparse](https://www.npmjs.com/package/pngparse) suggested in the discussion following [this comment](https://github.com/Khan/KaTeX/pull/264#discussion_r34209881) seems to only decode. Ideally, I'd use [optipng](http://optipng.sourceforge.net/) which has the added benefit of reducing the file size. But requiring a specific version of optipng to be installed doesn't feel right. Perhaps I can use emscripten to compile optipng (and its dependency libpng) to JavaScript and provide that as a Node module.

**Comment by kevinb7** [comment]
https://github.com/Khan/KaTeX/commit/90f9e12df3639633911f651ab8c3e20ff9f66081 contains all of the chrome screenshots which differ ever so slightly which is all of them.  This is on the https://github.com/Khan/KaTeX/commits/chrome_screenshot_images branch.

**Comment by gagern** [comment]
Except for `LimitControls` and `UnsupportedCmds` which were only added later, the images from your 90f9e12df3639633911f651ab8c3e20ff9f66081 and my b7e1581869ea4f5d20a6b7d7f0b0dc7bb4ae6f64 are the same. I still don't know what @xymostech  did to get those other results in ce99abd1f209b49680910fb9a93a7a45c0025f25. To verify the mentioned equality:

```sh
for i in test/screenshotter/images/*-chrome.png; do cmp --quiet \
<(git show 90f9e12df3639633911f651ab8c3e20ff9f66081:$i) \
<(git show b7e1581869ea4f5d20a6b7d7f0b0dc7bb4ae6f64:$i) \
|| echo $i differs; done
```

There are various JavaScript png encoders around, e.g. [pngjs2](https://www.npmjs.com/package/pngjs2) (which comes with a comparison of alternatives). However, they use node's own zlib package under the hood, so if that changes, then the results might not be reproducible. One possible approach would be starting with one of these packages, but swapping out the zlib package for something with a fixed version number (perhaps [pako](https://www.npmjs.com/package/pako)).

I also had a closer look at optipng. Unfortunately, compiling that to an in-memory-only node package via emscripten will probably be tricky, since it has synchroneous I/O tightly integrated with its optimization. At least if one were to call the official public library functions. I might have to call something more internal instead. As a bonus, optipng comes with its own copies of libpng and zlib, so that the result should be self-contained and yield perfectly reproducible results. If I ever get this far.

**Comment by gagern** [comment]
In https://github.com/gagern/KaTeX/commit/eabe35279d0e01e740fbd1e1218f16aa5713282c from [my pngRepack branch](https://github.com/gagern/KaTeX/commits/pngRepack) I've had a stab at creating PNG files in a reproducible fashion. Unfortunately the resulting files are considerably bigger than the ones created by Selenium itself.

**Comment by gagern** [comment]
PR #340 should resolve this, please consider merging it.

**Comment by kevinb7** [comment]
Closed by https://github.com/Khan/KaTeX/pull/340.  Thanks!
