### ISSUE TITLE
Vertical spacing between fractions in {matrix} environments is too tight

### ISSUE THREAD

**Issue by kevinb7** [Khan/KaTeX#331]
Reported by @mbourne in https://github.com/Khan/KaTeX/issues/312#issuecomment-125827083.

LaTeX:
<img width="176" alt="screen shot 2015-08-19 at 11 03 52 pm" src="https://cloud.githubusercontent.com/assets/1044413/9376170/b268de80-46c6-11e5-930a-5ab8b5f1ea4a.png">

KaTeX:
<img width="119" alt="screen shot 2015-08-19 at 11 04 03 pm" src="https://cloud.githubusercontent.com/assets/1044413/9376172/b58aa6fc-46c6-11e5-8f9d-ec80a2998e42.png">

MathJax:
<img width="88" alt="screen shot 2015-08-19 at 11 04 18 pm" src="https://cloud.githubusercontent.com/assets/1044413/9376174/bdf14120-46c6-11e5-945f-85b635251fc4.png">

I think we are almost doing the right thing with regards to LaTeX compliance.  I do however like the extra space that MathJax gives the fractions.  It seems like other people like the extra space too: http://tex.stackexchange.com/questions/33502/vertical-spacing-between-fractions-in-matrix-environment.

It may well turn out that this issue and https://github.com/Khan/KaTeX/issues/312 have the same root cause.

**Comment by mbourne** [comment]
Some examples from different browsers (all Win 7):

Firefox 39:
![image](https://cloud.githubusercontent.com/assets/7541940/9378135/99fb1986-4751-11e5-8d1c-14f27e2f4384.png)

Chrome 44:
![image](https://cloud.githubusercontent.com/assets/7541940/9378155/d2baa606-4751-11e5-8523-3b37830d7d0f.png)

IE 11:
![image](https://cloud.githubusercontent.com/assets/7541940/9378496/80a7d9ee-4754-11e5-86dc-000bae39eef3.png)

Regards
Murray

**Comment by gagern** [comment]
So what do we want? Compatibility with LaTeX, nice defaults, or a setting to switch between these two? Or some more fine-grained controls?

Internally LaTeX has no space between its row boxes, but each row box contains a strut, which ensures a minimal height and depth (of 0.7 resp. 0.3 of the common line height). A row with high content exceeds the dimensions of a strut, and therefore leads to touching content.

In my experience, this surprisingly is the right thing to do if you only have a few items of greater size in your matrix, since it tries hard to place the matrix rows at regular intervals. When the matrix contains mostly fractions, though, the setup looks indeed strange. But even with a bit of space, these are somewhat hard to read unless you make the space really big, the way MathJax apparently does. I'd be careful to deviate from LaTeX this far unconditionally. You can always add extra line height using the `\\[3ex]` notation or similar, and you can even copy&paste the tweaked formulas into a LaTeX document and expect similar rendering. Or use a solidus and write fractions on a single row, depending on your tastes.

**Comment by xymostech** [comment]
I vote for leaving it, and maintaining compatibility with LaTeX. It maybe causes some pain for users converting from MathJax or doing a MathJax fallback, but it's more consistent and heops people trying to do plain LaTeX -> KaTeX conversions.

**Comment by kevinb7** [comment]
Sounds good to me.

**Comment by mbourne** [comment]
This is probably sacrilege and no doubt a Bad Idea, but a simple fix that worked for me is setting the following style:

<code>.mfrac{font-size:0.9em}</code>

This gives me:

![image](https://cloud.githubusercontent.com/assets/7541940/9598853/a5d2b33a-50c1-11e5-9456-31393acd188d.png)

instead of:

![image](https://cloud.githubusercontent.com/assets/7541940/9598883/e590df24-50c1-11e5-9349-3136169786dd.png)

It's also OK with subscripts and super-superscripts:

![image](https://cloud.githubusercontent.com/assets/7541940/9599013/d14142e2-50c2-11e5-8e1d-155f83c5655d.png)

rather than...

![image](https://cloud.githubusercontent.com/assets/7541940/9599027/f3eb2c5e-50c2-11e5-98cb-bcb2a53c85b4.png)

Could it cause other problems?

Regards
Murray

**Comment by kevinb7** [comment]
@mbourne if you're using fractions in other expressions on your site with other non fraction expressions it might look a little weird.  Have you tried adding space in between lines using the `\\[3ex]` notation @gagern suggested?

**Comment by mbourne** [comment]
@kevinb7: 

(1) Actually, I quite like smaller fractions and currently have that style for my whole site, but sometimes fractions on fractions get too small. But that's overkill. Of course, it's possible just to target one matrix by enclosing it in a div and styling the mfracs in that div only

(2) Since I'm using ASCIIMath inpuit, it's a bit tricky to implement \\[3ex], which is why I looked for another solution. But actually, I think it would be a bit troublesome to have to add some spacing if you were doing a lot of matrices with fractions.

(3) I'm sure there's a reason, but the numerator of fractions in KaTeX always seem too high above the fraction bar to me.

In your screen shots at the beginning of this thread, if the 5 and 7 were lower, they wouldn't bleed into the 2 and 4 denominators of the above fractions.

I expect it is like this to give space for descenders, but is it possible to reduce the space when there is no descender involved?

Thanks to you and team for all your efforts.
Murray

**Comment by kevinb7** [comment]
> I'm sure there's a reason, but the numerator of fractions in KaTeX always seem too high above the fraction bar to me.

That's a good point.  It's quite possible that one of those screenshots was using `\displaymode` and the other wasn't.

**Comment by mbourne** [comment]
Emanuil's revisit of this issue triggered me to look at the numerator to fraction bar spacing issue again.

For the fraction 1/3, I got the following:

Ratio of {gap from number to fraction bar} to {height of numeral "1"} is around 25% in LaTeX, but around 60% in KaTeX. 

You can see this difference in Kevin's earlier screen shots in the opening post.

Even if the numerator involves descenders (and even if those descenders have subscripts with descenders), they don't touch the fraction bar.

![image](https://cloud.githubusercontent.com/assets/7541940/12546591/d341cd06-c385-11e5-8e05-fab16ffd9a12.png)


On the other hand, the spacing for denominators from the fraction bar looks good to me.

**Comment by edemaine** [comment]
@tomarshall A simpler equivalent approach would be to use a space character in the middle row:

```latex
\begin{bmatrix} 
    \frac{ 2 }{ 41 } & \frac{ -5 }{ 41 } \\ 
    ~ & ~\\
    \frac{ 7 }{ 41 } & \frac{ 3 }{ 41 } 
\end{bmatrix}
```

But these days you can also manually control the exact spacing using an optional argument to `\\`:

```latex
\begin{bmatrix} 
    \frac{ 2 }{ 41 } & \frac{ -5 }{ 41 } \\[1.5ex]
    \frac{ 7 }{ 41 } & \frac{ 3 }{ 41 } 
\end{bmatrix}
```

![image](https://github.com/KaTeX/KaTeX/assets/2218736/5affe56a-f295-4426-aac3-b4afd5a80b2e)
