### ISSUE TITLE
Simple expression breaks KaTeX

### ISSUE THREAD

**Issue by tarjei** [Khan/KaTeX#338]
Hi, this expression breaks KaTeX: 

`{\left[\matrix{{3}&{2}\\{4}&{3}}\right]}`

I thought that this was supported in 0.5. What am I missing?

**Comment by mbourne** [comment]
Hi Tarjei

The \begin{matrix} syntax will give you what you want:

{\left[\begin{matrix}{3}&{2}\\{4}&{3}\end{matrix}\right]}

Regards
Murray

**Comment by kevinb7** [comment]
In this case you can the `bmatrix` environment:
```
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
```

**Comment by tarjei** [comment]
Thanks for the comments :) Now I just have to get AsciiMath to output the correct syntax .

**Comment by mbourne** [comment]
@Tarjei: I am also using ASCIIMath input, and a hacked version of the original ASCIIMath -> LaTeX js by Peter Jipsen.

I ran up against the same issue as you (KaTeX didn't like \matrix, since it's not a LaTeX command).

Once I sorted that out, I got errors for 2 reasons:

(1) Too many enclosing braces:

KaTeX (and Codecogs, where I was testing things) would choke on multiple {{ }} like this:

\frac{{1}}{{{3x}^{{2}}}}

Codecogs would complain about incorrectly-nested braces, but in fact, they were OK. But removing most of the double- and triple-enclosed {{ }} did the trick (There seemed to be some limit over which Codecogs complained. It was happy with some of them, but not all.)

(2) Braces enclosing the matrix, like this

<code> \begin{matrix}{ ....... }\end{matrix}</code>

With those gone, everything seems to be sweet. (At least until I find something falls over because of a missing brace, but so far so good.)

Feel free to grab my hacked js. Current file name is ASCIIMathTeXKaTeX-2015-09-01.js

Here's an example page:

http://www.intmath.com/matrices-determinants/5-inverse-matrix.php

At some point I'm hoping the KaTeX folks will consider an ASCIIMath input option. :-)

Regards
Murray

**Comment by xymostech** [comment]
@mbourne Interesting stuff!

> KaTeX (and Codecogs, where I was testing things) would choke on multiple {{ }} like this:

I'm confused about why `\frac{{1}}{{{3x}^{{2}}}}` was breaking things. It seems to be working fine for me, maybe it was Codecogs' error?

> (2) Braces enclosing the matrix, like this

As far as I can tell, that isn't legal LaTeX (because the column delimiters and newlines have to be in the outer scope), so I can see why that wouldn't work. 

As for supporting ASCIIMath, that's probably not on the horizon for the moment. However, at this point we've sorta stabilized on an API where the parser spits out a (currently non-standardized) parse tree, and our two renderers (HTML and MathML) read that and produce appropriate output.

In the future, we might consider standardizing the parse tree, and then you could produce parsers that create that parse tree and renderers that render it, and you could mix and match (or combine, like how we currently do HTML and MathML at the same time).

For now, we're still adding features and changing things at a rapid enough rate that trying to standardize that interfacing parse tree would be a nuisance, but food for thought for the future!

**Comment by mbourne** [comment]
@xymostech I suspect after some thought these 2 issues were actually the same thing. In the fog of constant tweaking and testing, it was no doubt the step where I took out the <code>{matrix}{ ... }</code> inner braces when things started to work.

I'm aware it's not worth trying to hang other rendering systems on yet. But thanks for keeping it in mind for the future!
