### ISSUE TITLE
Add support for overbrace / underbrace

### ISSUE THREAD

**Issue by kynan** [Khan/KaTeX#365]

**Comment by kevinbarabash** [comment]
This is a little trick because we need to know how wide a layout is.  Currently we let the browser render things and stuff comes out being however wide it comes out.  I've added the ability to optionally generate metrics that include the width of glyphs, but it isn't being used by default.  It was more of an experimental feature that I thought might be useful in canvas rendering to avoid having to ask the canvas to measure each glyph during layout.  Regardless of the original intent of this option, it appears that width metrics will also be use in implementing these commands.

The thing the I'm struggling with is how to actually render the braces.  http://tex.stackexchange.com/questions/3488/horizontal-braces-with-xetex-take-too-much-space shows a redefinition of `\upbracefill` and `\downbracefill` which rotates the braces.  This seems reasonable considering there don't seem to be specific glyphs for these commands.  Since we're no longer supporting IE8 we could use CSS 2D Transforms, support matrix: http://caniuse.com/#feat=transforms2d.

**Comment by kevinbarabash** [comment]
This is in [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0).
