### ISSUE TITLE
Can I know customtag list used in katex??

### ISSUE THREAD

**Issue by Vnthf** [Khan/KaTeX#396]
such as ```<math> <mo> .. ```
Can I know custom tag list used in katex??

I add these tags to the whitelist at sanitize

**Comment by spicyj** [comment]
No, KaTeX doesn't accept MathML input. There's no way to add your own HTML tags to the output.

**Comment by velopert** [comment]
I think @Vnthf was asking the list of tags that are used in Katex so that he can implement the "generous whitelist" that is mentioned at [Katex/security.md].

You can check the list at:

https://github.com/KaTeX/KaTeX/blob/2b83935064bbd948c397caece0572a8b6b629c30/src/mathMLTree.js#L21-L28

For those people who will visit this issue in the future, I am leaving the code of my whitelist for html sanitizing.

```javascript
const tags = [
  'math',
  'annotation',
  'semantics',
  'mtext',
  'mn',
  'mo',
  'mi',
  'mspace',
  'mover',
  'munder',
  'munderover',
  'msup',
  'msub',
  'msubsup',
  'mfrac',
  'mroot',
  'msqrt',
  'mtable',
  'mtr',
  'mtd',
  'mlabeledtr',
  'mrow',
  'menclose',
  'mstyle',
  'mpadded',
  'mphantom',
  'mglyph',
];

// Following tags should be allowed for style property of span tag
const styles = [
  'background-color',
  'border-bottom-width',
  'border-color',
  'border-right-style',
  'border-right-width',
  'border-top-width',
  'border-style',
  'border-width',
  'bottom',
  'color',
  'height',
  'left',
  'margin',
  'margin-left',
  'margin-right',
  'margin-top',
  'min-width',
  'padding-left',
  'position',
  'top',
  'width',
  'vertical-align',
]
```

**Comment by kevinbarabash** [comment]
@velopert how would the `styles` array be used with the `trust` setting?
