### ISSUE TITLE
How to get variables from expression by KaTeX

### ISSUE THREAD

**Issue by duluosheng** [Khan/KaTeX#417]
I use KaTex to show my math expressions on web, but I get a trouble that I don't know how to get variables from expression by KaTeX. For example, I write a math expression "\sqrt{ a } + b - 3c + d", and it will output √​a​​​+b−3c+d, after that I want get the variables " a , b, c, d " to get the result of the expression. Does anybody can help me?

**Comment by kevinbarabash** [comment]
KaTeX is math typesetting software, it doesn't evaluate expressions.  You might look at something like http://jsep.from.so/ to do expression parsing.  Unfortunately it doesn't support TeX syntax.  The KaTeX parser is unsuitable for evaluation because it produces a data structure that describes where things should be position on the screen as opposed to an expression tree which describes the order things should be evaluated in.

**Comment by xymostech** [comment]
You could use something like [KAS](http://github.com/Khan/KAS), which should support what you are looking for. The README has instructions for parsing and evaulating.

**Comment by duluosheng** [comment]
Thank you for your answer @kevinbarabash @xymostech.
