### ISSUE TITLE
Indicate errors instead of showing an empty box

### ISSUE THREAD

**Issue by akerbos** [Khan/KaTeX#46]
When I use a command that is not supported or have unbalanced braces, KaTeX (at least its [demo](http://khan.github.io/KaTeX/)) won't output anything at all. That is bad for obvious reasons.

Instead, output an informative error message, ideally highlighting unknown commands and parsing the rest for syntactically well-formed expressions, or printing something like "too many {".

**Comment by kevinb7** [comment]
https://github.com/Khan/KaTeX/issues/273 will cover unsupported commands and https://github.com/Khan/KaTeX/issues/275 will update the docs to encourage users to use ```try```/```catch``` statements.  Since some people don't like having lots of console messages in production including them by default in the ```render``` call is out of the question.  We could have an option to do this, but since all calls to ```render``` should be wrapped in a ```try```/```catch```, it's just as easy to ```console.log``` the message there.
