### ISSUE TITLE
Array (or Tabular)  support is missing

### ISSUE THREAD

**Issue by lidel** [Khan/KaTeX#47]
One of less known use cases for TeX on a webpage is [ability to display data in tabular form][2].

The Other Library does not implement tabular but they [suggest][1] array environment as a replacement:

```tex
\begin{array}{c|cc}
\hline A & B & C\\
\hline D & E & F\\
\hline
\end{array}
```

which renders:

![](https://meta-discourse.global.ssl.fastly.net/uploads/default/34517/98bd1768b9e42654.png)

Sadly, I was unable to render the `array` above at http://khan.github.io/KaTeX/

btw: there is a related issue about matrices: #43

[1]: https://github.com/mathjax/MathJax-docs/wiki/LaTeX-Tabular-environment
[2]: https://meta.discourse.org/t/editing-an-insert-table-option/19719/5?u=lidel

**Comment by gagern** [comment]
My #246 which has just been merged provides the core functionality for arrays. But it doesn't do lines yet, neither horizontal nor vertical. Since lines were an essential part of the original post here, I'd leave this ticket open until lines are implemented as well. I have quite a number of things on my agenda, so if someone wants to take a stab at adding support for lines, feel free to do so.

**Comment by xymostech** [comment]
@gagern I'm actually going to close this and add a new issue to specifically add horizontal and vertical lines. I think that will make it clearer why this issue is open.
