### ISSUE TITLE
Support `\middle`

### ISSUE THREAD

**Issue by xymostech** [Khan/KaTeX#527]
Initially found in https://github.com/Khan/KaTeX/issues/526

It's pretty clear what this function is supposed to do (the same thing as `\left` and `\right`, but inside of that expression). It doesn't exist in TeX though, and I can't figure out where it's defined in LaTeX, which is terribly confusing.

**Comment by asmeurer** [comment]
In case anyone comes here looking for a workaround, you can use

```
\left.\left( \frac{1}{x} \right| x  \right)
```

if the left side is larger and

```
\left( x \left| \frac{1}{x} \right) \right.
```

if the right side is larger (I don't think there's a uniform workaround for both cases, which is probably why `\middle` exists in the first place).

**Comment by gagern** [comment]
> It doesn't exist in TeX though

It's part of e-TeX. `pdftex` and `latex` will probably support it, since they both are based on the pdfTeX engine which includes e-TeX, at least in Texlive 2016. Plain `tex` doesn't support it, but `etex` does. You may want to look at [`pdftex.web`](https://foundry.supelec.fr/scm/viewvc.php/tags/1.40.17/source/src/texk/web2c/pdftexdir/pdftex.web?view=markup&revision=757&root=pdftex) to find more about its implementation. So it's a primitive command and we should implement it as such.

**Comment by xymostech** [comment]
@gagern Ah, very cool!
