### ISSUE TITLE
\color causes incorrect spacing with some adjacent elements when `\displaystyle` is present in the coloured block

### ISSUE THREAD

**Issue by daniel3735928559** [Khan/KaTeX#533]
**Steps performed**: On either of Chromium 53 or Firefox 48.0.2 (both on Linux), navigated to https://khan.github.io/KaTeX/ and entered `\color{red}{\displaystyle\int x}+1` and `\displaystyle\int x+1` into the "Type an expression" box.

**Expected behaviour**: The two expressions should look the same, but one having the integral coloured red and the other not.

**Observed behaviour**: In the coloured version, there is very little space between the x and the + compared to in the non-coloured version.

This issue also exists when testing locally by running `node server.js` on a local clone of KaTeX.  It seems to be related to the use of `\displaystyle`, since without that it behaves as expected (though then the integral is rendered smaller on the local version; for some reason in the online demo the integral is rendered at displaystyle size regardless.)

I made a brief effort to chase this up but don't have time to get into it in the immediate future, so I thought I'd document it in case someone else runs into it or knows a quick fix.

**Comment by kevinbarabash** [comment]
@daniel3735928559 thanks for the report.  I was able to reproduce this.  MathJax and LaTeX handles make sure the correct space is there.  In the markup we wrap the group in a `<span>`, but this makes solving the problem complicated because we can't make the wrapper an `mord` because then spacing on the left side of the group might be wrong.  Maybe there's a way that we can output groups without the extra `<span>` wrapper if it's not needed.

**Comment by kevinbarabash** [comment]
`{\displaystyle\int x}+1` renders correctly, so in that case we're not adding an extra `<span>` around `\int x`.  Also, the color is applied independently to each glyph.
