### ISSUE TITLE
Release unminified js and css

### ISSUE THREAD

**Issue by Munken** [Khan/KaTeX#547]
Currently working on integrating KaTeX into gitlab. Here it is a no-go to include minified sources. 

Would it be possible to also distribute the non-minified versions?

Gitlab MR: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4638

**Comment by connorshea** [comment]
Unfortunately since KaTeX uses LESS we can't reasonably add it directly to our assets since we use SCSS and would rather not have two parsers to deal with.

Similarly, the JS is fairly complex so an unminified-but-compiled katex.js would be great rather than having to convert the build process to work with our asset pipeline.

Would be happy to work with you guys/gals on this :)

**Comment by deckar01** [comment]
> `.SECONDARY` - The targets which `.SECONDARY` depends on are treated as intermediate files, except that they are never automatically deleted.

https://www.gnu.org/software/make/manual/html_node/Special-Targets.html

These unminified file names can be marked as "secondary" so that they are included in the release.
