### ISSUE TITLE
Dropdown menu displays both KaTeX-MathML and KaTeX-HTML

### ISSUE THREAD

**Issue by SamanthaYu** [Khan/KaTeX#572]
The dropdown menu displays both the KaTeX-MathML (including the annotation) and KaTeX-HTML elements so the math symbols appear to be rendered on both sides of the annotation.
<img src="https://cloud.githubusercontent.com/assets/10355013/20651977/69fc9f62-b4a5-11e6-90ea-e380c1515eec.PNG" width="150">
It seems to be an HTML issue, because I tried to hide the MathML with JavaScript (by setting the visibility to hidden, and display to none), and it does not affect the dropdown menu. In other words, hidden elements still appear in the dropdown menu.

In the end, I fixed it by getting rid of the MathML elements in the dropdown menu:
``$('option .katex-mathml').remove();``

Now, the dropdown menu looks like this:
<img src="https://cloud.githubusercontent.com/assets/10355013/20651966/37df82d8-b4a5-11e6-9d81-f688b6094a0d.PNG" width="100">
It's probably not the best solution but more of a temporary fix until this issue gets resolved someday.

**Comment by gagern** [comment]
I feel like I'm missing some context here. What dropdown menu would that be?

**Comment by xymostech** [comment]
@SamanthaYu It would be nice if you added some code, but I think you're trying to put KaTeX-rendered math inside of your `<option>` tags in your dropdown?

`<option>` elements can only contain text, not markup tags like what KaTeX produces, which is why you're seeing all of the text that is contained in the markup that KaTeX produces. Since the markup contains MathML, that text is displayed as well.

So, KaTeX doesn't support rendering math in dropdowns. You should just copy the individual characters that you want (like `±`, `∫`, `θ`, `π`) and put those directly in your `<option>` elements.

**Comment by SamanthaYu** [comment]
Sorry for the missing context, but yes, I was trying to put KaTeX-rendered math instead of the `<option>` tags.

Thank you, @xymostech, for clearing that up! That makes a lot of sense.
