### ISSUE TITLE
Accept more whitespace characters in regexes

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#583]
Currently many of our regexes only allow spaces where LaTeX also accepts tabs.

**Comment by gagern** [comment]
The way I read the Lexer, we [allow for any sequence of whitespace](https://github.com/Khan/KaTeX/blob/4a9c2acbf7a50a6205cc3f42f374a4b3047c9bf1/src/Lexer.js#L80) and [replace it with a single space](https://github.com/Khan/KaTeX/blob/4a9c2acbf7a50a6205cc3f42f374a4b3047c9bf1/src/Lexer.js#L102). So anything that deals with post-lexer tokens should not have to care about the exact notation of whitespace, unless you're implementing something like `\verb` which would be really hard at the moment.

Are you saying this doesn't work as it should? Judging from https://github.com/Khan/KaTeX/pull/579#discussion_r91599472 this issue here was opened without actually trying out that feature with tabs in the input. In my opinion it should simply work. Perhaps we should add some unit tests to verify that the exact formatting of whitespace doesn't affect the parsed result, for all the various space-containing regexes as well as for regular typeset white space in text and math mode.
