### ISSUE TITLE
how to use "&" in xhtml... it's shows error when I use "&" within \begin{vmatrix}

### ISSUE THREAD

**Issue by AJBALA** [Khan/KaTeX#592]
Even escaping sequence \& is not working to save the xhtml file. 

my code:
<div class="equation">
$$\mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} &  \frac{\partial Y}{\partial u} & 0 \\
\frac{\partial X}{\partial v} &  \frac{\partial Y}{\partial v} & 0
\end{vmatrix}$$
</div>

**Comment by gagern** [comment]
In XHTML you'd have to either [escape](https://en.wikipedia.org/wiki/XML#Escaping) the `&` as `&amp;` or enclose it in a [CDATA section](https://en.wikipedia.org/wiki/CDATA). You could for example enclose the whole formula in a CDATA section like this: `<![CDATA[$$ … $$]]>`. If neither of these works for you, you should be more specific: Describe the error you observe (error message or incorrect rendering?), provide a [short, self-contained, otherwise correct reproducing example](http://www.sscce.org/) or point out a web site where we can see the problem.

**Comment by AJBALA** [comment]
I used escaping character but still the math is not working. This is my code:
$$\begin{bmatrix} 0 &amp; \cdots &amp; 0 \\ \vdots &amp; \ddots &amp; \vdots \\ 0 &amp; \cdots &amp; 0 \end{bmatrix}$$

Also below <![CDATA[$$ … $$]]> is not used by replacing escapting character &amp; into & but still is not working.

<![CDATA[$$\begin{bmatrix} 0 &  \cdots &  0 \\ \vdots &  \ddots &amp; \vdots \\ 0 &  \cdots &  0 \end{bmatrix}$$]]>

Thanks,
Bala AJ

**Comment by gagern** [comment]
Please actually *read* [my previous comment](https://github.com/Khan/KaTeX/issues/592#issuecomment-269617209)! We need a detailed description of the error (more detailed than “not working”), and either a copy of the XHTML file, ideally without unrelated content, or a URL where we can see the problem. You can attach files to GitHub issues by drag and drop or file selection; see the description below the comment input box. HTML files are not supported, so you may have to zip the file. I will not repeat this request for details again.

I've just tested that rendering your formula (first version) works in an XHTML file. See [katex592.zip](https://github.com/Khan/KaTeX/files/682042/katex592.zip) for the file I used.

**Comment by AJBALA** [comment]
Thank you so much. I got it.. Sorry for the trouble. One more thing I noted that some alignment issue in chrome for the below formula. i.e. each rows are touching together. If you have quick solution then let me update.    

Thanks in Advance!

		$$  \mathbf{V}_1 \times \mathbf{V}_2 =  \begin{vmatrix}
\mathbf{i} &amp;   \mathbf{j} &amp;   \mathbf{k} \\
\frac{\partial X}{\partial u} &amp;   \frac{\partial Y}{\partial u} &amp; 0 \\
\frac{\partial X}{\partial v}  &amp;   \frac{\partial Y}{\partial v} &amp; 0
\end{vmatrix}$$

**Comment by gagern** [comment]
You know, it would have been kind of nice to indicate what the actual problem was, and how you have fixed it now. That way other users searching our list of issues would be more likely to find your description and apply the same solution to their scenario. Perhaps there also is some documentation we should be adding somewhere.

See #331 for the vertical spacing in your matrix.
