### ISSUE TITLE
\textellipsis and \mathellipsis (was \dots)

### ISSUE THREAD

**Issue by edemaine** [Khan/KaTeX#596]
KaTeX does not support the macro `\dots` which is a synonym for `\ldots`.  Also, it seems that both are supposed to work in text mode in addition to math mode. Here's the source, from `latex.ltx` and `fontmath.ltx`:

```latex
% fontmath.ltx
\def\mathellipsis{\mathinner{\ldotp\ldotp\ldotp}}%
% latex.ltx
\DeclareTextCommandDefault{\textellipsis}{%
   .\kern\fontdimen3\font
   .\kern\fontdimen3\font
   .\kern\fontdimen3\font}
\DeclareRobustCommand{\dots}{%
   \ifmmode\mathellipsis\else\textellipsis\fi}
\let\ldots\dots
```

Also suggests we should add the macros `\textellipsis` and `\mathellipsis` which work only in their respective mode.  Looks like there are a lot of other related `\text...` and maybe `\math...` symbols that are missing too, e.g. `\texttrademark` and `\textregistered`.  I'll work on a pull request...

**Comment by gagern** [comment]
`\dots` is discussed in #528. The problem is that with AMSMath it *sometimes* behaves like `\cdots`, and that's the behavior we'd like to model.

I'm not sure how important `\mathellipsis` is, but I guess we could add that, as a synonym to `\ldots` in our case. `\textellipsis` might be worth more discussion, since some might argue that the proper way of representing that would be using the unicode codepoint U+2026 to ensure that the meaning is retained if the text gets copied and pasted. Not sure whether that is relevant.

For trademark, registered and so on I guess we simply don't have the symbols included in our fonts. Otherwise #286 should have caught them.

**Comment by edemaine** [comment]
Sorry, this is a duplicate then.  I'll try to implement the amsmath behavior, but continue discussion on #528.

**Comment by edemaine** [comment]
P.S. If I understand `symbols.js` correctly, `\ldots` is already defined to be the unicode codepoint U+2026.  So should both `\textellipsis` and `\mathellipsis` do the same?

**Comment by gagern** [comment]
If we have a unicode symbol for this, then yes, by all means, make `\textellipsis` and `\mathellipsis` do the same, in their respective modes. I'd welcome a pull request to that effect.
