### ISSUE TITLE
Warn when using an XHTML DOCTYPE

### ISSUE THREAD

**Issue by oddhack** [Khan/KaTeX#601]
I see several other open issues about fractions, but I think this is different, and so badly rendered that I'm wondering if I'm doing something obviously bogus (first-time KaTeX user here).

There's a test case with a couple of fractions at http://alumnus.alumni.caltech.edu/~jon/frac.html . This uses KaTeX 0.6.0 from the CDN, which I believe to be current.

And I've attached an image showing rendering in Chromium 55 / Debian 8 (same results with current Firefox). I've tried scaling up and down between about 50% - 200% and it looks just as bad in all cases.
![frac](https://cloud.githubusercontent.com/assets/4693344/21681105/87e8aa54-d302-11e6-9faa-18a854108487.gif)

**Comment by oddhack** [comment]
N.b. here's the math I'm trying to render, extracted from the HTML for future reference: 

\[ half = \frac{1}{2} \]
\[ f = \frac{c}{{2^b - 1}} \]
\[ max_{clamped} \over {2^{(exp'-B-N)}} + \frac{1}{2} \]

**Comment by kevinbarabash** [comment]
@oddhack I noticed you're using an XHTML doctype, try `<!DOCTYPE html>` and see if that fixes it.

**Comment by edemaine** [comment]
@kevinbarabash In local testing, that was indeed the problem.  I see that KaTeX has a warning for quirks mode; maybe it can also have a warning for XHTML mode?  (And maybe someday XHTML support... if that is important.)

**Comment by kevinbarabash** [comment]
@edemaine thanks for testing that out.

**Comment by xymostech** [comment]
@oddhack I did a bunch of digging into what is causing this problem. It like there's a difference in rendering between XHTML and HTML 5, maybe due to the limited-quirks mode (which is like quirks but with fewer quirks, and which is turned on in XHTML 1.0): https://quirks.spec.whatwg.org/#the-line-height-calculation-quirk

I made a minimal (I think) repro case for what's going on here: http://jsbin.com/fihiboqopu/1/edit?html,css,output If you replace the doctype with the XHTML one, you'll see the "2" inside of the box shift vertically a little bit. This is a reproduction of the HTML that KaTeX uses to vertically position things. Because of that difference, fractions render poorly when using XHTML. This same thing happens in quirks mode, (i.e. if you remove the doctype completely the same thing happens), which leads me to believe it has something to do with limited-quirks mode.

I think that adding the warning like we're doing in #602 is helpful, since it'll let people know what the problem is. However, it would be great if we actually just supported XHTML, since people are probably using it. It looks like there might just be this small thing wrong, and it's probably fixable (admittedly it's probably not going to be _easy_ to solve; the current incantations we currently use to make the vertical positioning work in many different browsers is terrifying).

**Comment by gagern** [comment]
Thanks for the example, @xymostech. Experimenting a bit with that, it seems that the problem isn't so much about XHTML vs. HTML, but more about Transitional HTML 4 vs. strict HTML 4 or HTML 5. If you change the header to

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
```

you get the same rendering as you get with the HTML 5 header,  but with

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
```

the problem shows up. At least in my Firefox. In more detail, the problem may be due to the `display: inline-block` rule. Changing that to `block` yields results in strict that look just like they do for transitional. I guess the issue might have something to do with [Almost Strandards Mode](https://developer.mozilla.org/en-US/docs/Gecko's_Almost_Standards_Mode) in Gecko. Apparently that's called [limited quirks mode](https://dom.spec.whatwg.org/#concept-document-limited-quirks) now, and standardized in a cross-browser fashion. Reading that standard, I see no reference to `inline-block`. [The blocks ignore line-height quirk](https://quirks.spec.whatwg.org/#the-blocks-ignore-line-height-quirk) sounds like our best bet, as it applies to limited-quirks mode, too, and has something to do with box heights and therefore vertical placement.

Putting a zero-with space U+200B into the `#e` container in your example, directly following `#f`, seems to fix the problem. It breaks the quirk rule of only having inline-level elements inside the block. So we need to find a way to introduce these into our DOM (unconditionally or if we detect limited-quirks mode) in such a way that it doesn't break any of our CSS spacing rules that are based on adjacent elements.

> However, it would be great if we actually just supported XHTML, since people are probably using it.

I agree. If everything else fails, we might consider detecting such setups and putting the whole formula into an `<iframe>` with a `data:` URI as source. But this would be ugly in terms of styling, so I too hope that we find some more elegant way to avoid this problem.

**Comment by edemaine** [comment]
Limited-quirks 3.3 and 3.4 of the [quirks spec](https://quirks.spec.whatwg.org/#the-line-height-calculation-quirk) seem relevant, though I haven't fully deciphered/tested whether they are indeed causing the problem, and whether there's a work-around.

**Comment by edemaine** [comment]
Reading @gagern's post more carefully, adding some zero-width spaces when limited quirks mode detected (as described by @gagern in https://github.com/Khan/KaTeX/pull/602#issuecomment-270891096) seems a reasonable approach (though the CSS issues sound... exciting).  It isn't quite clear to me where this would be required.  I tried adding `&#8203;` to every span in http://alumnus.alumni.caltech.edu/~jon/frac.html and it didn't fix the frac issue...

Another question is whether limited quirks is that important.  We could instead suggest that people "upgrade" to XHTML 1.0 Strict, XHTML 1.1, or XHTML Basic 1.1 ([DTD options](https://www.w3.org/QA/2002/04/valid-dtd-list.html#DTD) that don't match limited-quirks mode).  Hmm, the [differences](https://24ways.org/2005/transitional-vs-strict-markup) seem severe, e.g., no `<iframe>` support.  So maybe not a great outcome.

**Comment by xymostech** [comment]
@gagern

> Putting a zero-with space U+200B into the #e container in your example, directly following #f, seems to fix the problem. It breaks the quirk rule of only having inline-level elements inside the block. So we need to find a way to introduce these into our DOM (unconditionally or if we detect limited-quirks mode) in such a way that it doesn't break any of our CSS spacing rules that are based on adjacent elements.

Ah ha! Wonderful! I was trying to put elements after `#e`, but I guess I don't understand the quirk well enough. Did this fix it with the HTML 5 doctype and the XHTML doctype? It looks like it does to me. If so, we should just try adding that space! Maybe it'll fix the problem. It might cause others, but hopefully they will be caught by the screenshot tests? I've blocked off some time later today to do a release, I'll play around with that as well.

**Comment by xymostech** [comment]
(I just played around with it, it looks like it does in fact solve the problem, in both doctypes!)

**Comment by gagern** [comment]
@oddhack, can you give the code from #607 a try?
