### ISSUE TITLE
Display equations are not centered

### ISSUE THREAD

**Issue by feuerbach** [Khan/KaTeX#626]
Hi.

I am considering switching from MathJax to KaTeX. I couldn't find any simple examples of html code with KaTeX, so here is what I came up with (this is roughly what `pandoc --katex` generates):

    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Test</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css" integrity="sha384-wE+lCONuEo/QSfLb4AfrSk7HjWJtc4Xc1OiB2/aDBzHzjnlBP4SX7vjErTcwlA8C" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js" integrity="sha384-tdtuPw3yx/rnUGmnLNWXtfjb9fpmwexsd+lr6HUYnUY4B7JhB5Ty7a1mYd+kto/s" crossorigin="anonymous"></script>
        <script type="text/javascript"> window.onload = function(){ var mathElements = document.getElementsByClassName("math"); for (var i=0; i < mathElements.length; i++) { var texText = mathElements[i].firstChild; katex.render(texText.data, mathElements[i]); } }
      </script>
      </head>
      <body>
        <p><span class="math display">\displaystyle \frac{\theta_i/l_i}{\sum_{k=1}^{M}\theta_{k}/l_{k}}</span></p>
        <p><span class="math display">\displaystyle p(G,S,R|\theta)=\prod_{n=1}^N p(G_n|\theta)p(S_n|G_n)p(R_n|G_n,S_n).</span></p>
      </body>
    </html>

The formulas render, but they are not centered despite being declared as
`\displaystyle`:
![katex](https://cloud.githubusercontent.com/assets/24844/21961425/2849c1a6-db12-11e6-902e-7ff2c96449b5.png)

Am I doing something wrong here?

**Comment by gagern** [comment]
You are essentially doing the equivalent of `$\displaystyle …$` in TeX. It does use display style within the formula, but still includes the formula as a whole into the surrounding context in an inline fashion. To achieve something like `$$…$$` you would usually do `katex.render(…, …, {displayMode: true})`. That will enable [a CSS rule](https://github.com/Khan/KaTeX/blob/v0.6.0/static/katex.less#L6-L15) that should give you centered content. It also makes the `\displaystyle` command inside the formula redundant.

I guess I'd use [the `DOMContentLoaded` event](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded) instead of `window.onload` to ensure that formulas get typeset while images are still being loaded. Or you simply embed the corresponding script at the end of the `<body>`. Both of these approaches are [suggested in the auto-renderer documentation](https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/README.md).
