### ISSUE TITLE
using render(...).success(...).error(...) format rather than throwing?

### ISSUE THREAD

**Issue by Pomax** [Khan/KaTeX#64]
Given the rising popularity of promisses and the Node approach of success/error routing rather than throwing errors, it might be nice to make the `.render` and `.renderToString` functions return objects that can bind `success` and `error` handlers. That way it's much easier to write things like
```
katex.renderToString("f(x) = 2y")
     .success(function(html) {
       // inject html code wherever needed now
     } )
     .error(function(error) {
      // okay this clearly didn't work, let's fall back to something else
     });
```

**Comment by kevinb7** [comment]
I think that https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/auto-render.js makes things a lot better for the average user who just wants all their math to be rendered by handling exceptions appropriately.

The issue of people using the API directly being caught off guard should probably be handled by updating the examples in the docs to include a ```try```/```catch``` block as well as a warning to always catch errors.

> The success-error pattern is kind of a hack for async programming without coroutines because async operations can’t use throw-catch. This makes sense if renderToString is async, but it’s not.

Totally agree.  

```async```/```await``` (part of ES7) supports ```try```/```catch```/```throw``` for asynchronous code.  I can't wait to use it.  It really cleans up a lot of the clutter that you get with Promises.

Since Promises add clutter and aren't necessary b/c all of the code is synchronous there isn't really a reason to support them.  @Pomax if you really want to use Promises it shouldn't be too difficult to write a wrapper around ```renderToString```.

I'm going to close this and will update the docs.

**Comment by Pomax** [comment]
I mostly just want code that I can use as both user as well as dev (some things need immediate loading, but a page like http://pomax.github.io/bezierinfo, no matter how fast katex renders, *needs* on-demand loading instead of loading up front =D). If you're going to stick with try catch, that's aesthetically very ugly, but from a functional point of view perfectly fine. I don't really agree with the fact that success/error is a hack, but that has no bearing on keeping the issue closed, really.

**Comment by kevinb7** [comment]
How do you do the on-demand loading?  Can you point me at some code?

**Comment by kevinb7** [comment]
@Pomax have you tried calling ```renderToString``` in a web worker and then passing the HTML back?

**Comment by kevinb7** [comment]
If you ```throw``` inside of a Promise, it should catch the except and pass the value to the error handler.  If there's no error handler then it still blows up.
```
var promise = new Promise(function (resolve, reject) {
   if (eqnInView) {
      katex.render(equation, container);
      resolve();
   }
   var listener = document.addEventListener('scroll', function (e) {
      if (eqnEnteringView) {
         document.removeEventListener(listener);
         // okay if this throws as long as there's a error handler
         katex.render(equation, container);
         resolve();
      }
   };
});

promise.then(function () {
   console.log("success");
}, function (err) {
   console.log(err);
});
```

**Comment by spicyj** [comment]
I could imagine us returning some sort of success/error object but it would probably not be a promise.

**Comment by Pomax** [comment]
@kevinb7 currently it's using MathJax, with the dynamic loading happening in https://github.com/Pomax/bezierinfo/blob/gh-pages/js/sectionloading.js
