### ISSUE TITLE
KaTex failed to load Chemical equation

### ISSUE THREAD

**Issue by gvnavin** [Khan/KaTeX#669]
I tried the below latex snippet, which is a some chemical equation. Katex failed to render the below. 

`
S{O}_{4}+\downarrow 2H\overset{{H}_{2}S{O}_{4}+2{S}_{4}}\rightarrow{H}_{2}+S{O}_{4}\uparrow \xrightarrow[{\Delta }]{{H}_{2}}HCl+H2\phantom{\rule{0ex}{0ex}}
`

I created this equation from the below online tool.
http://www.imatheq.com/imatheq/com/imatheq/math-equation-editor-latex-mathml.html

Added the image with the equation for the reference.
![image](https://cloud.githubusercontent.com/assets/1912988/24403883/8b71abec-13dc-11e7-9fbe-ff754ba6045c.png)

**Comment by sthoch** [comment]
KaTeX does not support some of the functions that the formula uses, c.f. [the wiki](https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX).

However, there is a [workaround for `overset`](https://github.com/Khan/KaTeX/issues/484#issuecomment-223895628) and you could try to emulate the `xrightarrow` manually using dashes and negative spacing, like `-\mkern{-0.38em}-\mkern{-0.38em}\rightarrow` ...

**Comment by kevinbarabash** [comment]
https://github.com/Khan/KaTeX/pull/605 has been merged so there is now support for `overset` on `master`.

**Comment by abnerlee** [comment]
+1

**Comment by kevinbarabash** [comment]
LaTeX and KaTeX both render the given equation as:
<img width="593" alt="screen shot 2017-09-06 at 6 38 17 am" src="https://user-images.githubusercontent.com/1044413/30107854-02871738-92ce-11e7-8a0c-e830d2c5fe63.png">

In order to have a stretchy arrow between the two sides of the equations use:
```
S{O}_{4}+\downarrow 2H\xrightarrow{{H}_{2}S{O}_{4}+2{S}_{4}}{H}_{2}+S{O}_{4}
\uparrow \xrightarrow[{\Delta }]{{H}_{2}}HCl+H2\phantom{\rule{0ex}{0ex}}
```

This produces the following output in LaTeX and KaTeX:
<img width="995" alt="screen shot 2017-09-06 at 6 40 48 am" src="https://user-images.githubusercontent.com/1044413/30107939-58b0807c-92ce-11e7-8e9e-fbee998e6aff.png">

**Comment by kevinbarabash** [comment]
I believe that imatheq.com's LaTeX output is incorrect in using:
```
\overset{{H}_{2}S{O}_{4}+2{S}_{4}}\rightarrow
```
and should instead be
```
\xrightarrow{{H}_{2}S{O}_{4}+2{S}_{4}}
```
