### ISSUE TITLE
Delimiter support for renderToString function

### ISSUE THREAD

**Issue by keshavkaul** [Khan/KaTeX#672]
Hi,
I'm having Textual and Mathematical expressions contained in a string variable. Whenever I pass this string variable into `renderToString` function, I get the whole string parsed as a mathematical expression. Instead, I would like it to only parse those sections in the string that I designate as mathematical expressions. Can we do this currently? If so how? and if not what are the alternatives?

**Comment by xymostech** [comment]
KaTeX only supports rendering math expressions for now (except for text expressions embedded in math, like `\text{}`). We do have an extension which will parse out math expressions from a DOM component in https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/auto-render.js but that is purely on the client side currently.

What is your use case for this? You could maybe use that extension on the client side. Or, you could take the code in there to do the parsing on the server?

**Comment by keshavkaul** [comment]
@xymostech Thanks for the quick response. I'm making a react native project and I'm using `katex` via npm. I had planned on storing mathematical expressions along with custom stylized HTML text and pass it on to katex to render the final html. Since this is not currently possible with `renderToString`, I could start writing a PR for this feature. I have checked `auto-render.js` as well and would like to add the delimiter option into the options object that we pass to `renderToString` function. I would appreciate if you could let me know if this aligns with the project's goal. Thanks

**Comment by edemaine** [comment]
A text-level parser, that looks for the `$...$` etc. delimited math, is what I was hoping to do for #604.  This would differ from `auto-render` in that it would still be a string-to-string transform, instead of being done directly on the DOM.  I still think it's a good thing to do, and perhaps this interest will prompt me to give it a try (as an additional contrib library).

Meanwhile, here is some other MIT-licensed code that does this (but in a more complicated setting, so you'd need to extract the relevant bits, which is what I'd be doing for #604): https://github.com/edemaine/coauthor/blob/master/lib/formats.coffee
If you have time to do this extraction, feel free to turn it into a PR!

**Comment by keshavkaul** [comment]
@edemaine Thanks for the direction. 👍  I shall have a look at `formats.coffee` over the weekend!

**Comment by edemaine** [comment]
I suggest continuing any further discussion over on #604.
