### ISSUE TITLE
Integral symbol is chopped off when output is larger than draw area

### ISSUE THREAD

**Issue by phoenixeliot** [Khan/KaTeX#68]
Split from this: https://github.com/Khan/KaTeX/issues/56

Integral symbols are chopped off strangely when the formula you enter is too long for the area it's in.

![screen shot 2014-09-16 at 5 02 41 pm](https://cloud.githubusercontent.com/assets/491376/4298621/0cb69e9e-3e27-11e4-9ee5-c226daa05058.png)

![screen shot 2014-09-16 at 5 02 49 pm](https://cloud.githubusercontent.com/assets/491376/4298617/f936423e-3e26-11e4-800e-cb705e55b7d9.png)

Operating system: OSX 10.9.4 (others untested)
Browser: Chrome (but NOT Firefox or Safari)
Retina screen (normal resolution untested)

**Comment by kevinb7** [comment]
We might be able to fix this using `padding-right` instead of `margin-right`.

Rendered using `padding-right`:
<img width="368" alt="screen shot 2015-07-16 at 1 26 36 pm" src="https://cloud.githubusercontent.com/assets/1044413/8732995/5b3dfa78-2bbe-11e5-93ee-570d505f468d.png">

Rendered using `margin-right`:
<img width="352" alt="screen shot 2015-07-16 at 1 32 05 pm" src="https://cloud.githubusercontent.com/assets/1044413/8733135/45bdb9a8-2bbf-11e5-9fa3-9efb48aa8482.png">

**Comment by peterjeliot** [comment]
Maybe I'm missing something, but the integral symbols look the same on those (only the right edge is different)

**Comment by kevinb7** [comment]
@peterjeliot in the first image the rendered math is wider than the container.  If it were using `margin-right` the integral sign would have been clipped, but it's using `padding-right` which prevents the clipping for some reason.  In the second image, the rendered math is narrower that the container and it's using the original `margin-right` so it shows what the integral signs normally look like.   The rendering of the integral signs might actually be the same between the two. I'll have to try the change out and run the screenshot tests.

**Comment by spicyj** [comment]
@kevinb7 padding-right on which element? All of them?

**Comment by kevinb7** [comment]
@spicyj I put `padding-right` right just on the integral signs.  I'll have a to see what happens if I replace all uses of `margin-right` with `padding-right`.  In terms of layout it shouldn't matter (famous last words).

**Comment by kevinb7** [comment]
I tried this change out in the test app and using `padding-right` moves the limits ever so slightly closer to the integral sign.  This is a big issue because the spacing of our rendering differs far from LaTeX.  Green is LaTeX, red is KaTeX.

`padding-right`:
![integrals](https://cloud.githubusercontent.com/assets/1044413/8843463/cbc26962-30c5-11e5-81ac-82ebe56c0d3f.png)

`margin-right`:
![integrals](https://cloud.githubusercontent.com/assets/1044413/8843475/dd7b9912-30c5-11e5-9540-5d99d2ec3a64.png)

**Comment by kevinbarabash** [comment]
I'm not seeing this issue anymore in Chrome.  @phoenixeliot please re-open if you're still experiencing it.
