### ISSUE TITLE
Auto-render extension and ReactJS

### ISSUE THREAD

**Issue by shenkev** [Khan/KaTeX#700]
Does the Auto-render extension support ReactJS? Is there a working example?

**Comment by xymostech** [comment]
Here's an example of using the auto-render extension with ReactJS. It works, but it's probably not really what you want, because React might get mad that you modified the nodes out from under it: http://jsbin.com/fowucomayu/edit?html,js,output

At Khan Academy, when we want to put math in our React, we use a `<TeX>` component that we wrote. It uses both KaTeX and MathJax, so you might want to adapt it to your needs, but it probably is a better way to put math in your React.

Example: http://khan.github.io/react-components/#tex  
Code: https://github.com/Khan/react-components/blob/master/js/tex.jsx

**Comment by edemaine** [comment]
@xymostech Is it worth linking to http://khan.github.io/react-components/#tex from KaTeX documentation?

**Comment by xymostech** [comment]
Probably! I guess if we're linking to it from the `KaTeX` docs I'd prefer if it were linking to a component that didn't require people to include MathJax, but it's a good starting point!

**Comment by kevinbarabash** [comment]
It would be nice to have a `<KaTeX>` component, but it probably makes sense to have that as a separate repo.
