### ISSUE TITLE
replace version numbers in urls targeting to KaTeX with "latest"

### ISSUE THREAD

**Issue by redstoneleo** [Khan/KaTeX#715]
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
```
I suggest to replace version numbers in above urls targeting to KaTeX with "latest" and do some redirections , so that we won't need to update current urls so as to use the latest version of KaTeX. BTW, MathJax already did this way !

**Comment by edemaine** [comment]
`https://cdnjs.cloudflare.com/ajax/libs/KaTeX/latest/katex.min.js` doesn't work.  Do you know how to get CDN to work this way?

**Comment by redstoneleo** [comment]
I have never did that thing,  but I think you have to redirect 
`https://cdnjs.cloudflare.com/ajax/libs/KaTeX/latest/katex.min.js`
to the latest version of KaTeX, for example,  to  
`https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js` currently .

**Comment by mbourne** [comment]
I understand MathJax could point to "latest" because they were running their own server, which they recently retired. Their latest recommendation for the Cloudflare CDN includes the version number (not including a "latest" in the URL).

If I was using the CDN version of KaTeX, I would probably proceed as follows (assume I'm using PHP):

Write a script that starts at the latest known version, 0.7.1, then looks at the headers for the next version, 0.7.2.

If that returns a 200, great, the KaTeX ppl have updated, maybe I''ll use that.

Try the next one: 0.7.3.

That returns a 404, so it means KaTeX is not up to that yet.

So fall back, and use 0.7.2.

My variable would be $latestKatexCDNVers = '0.7.2';

My script call would then be:
https://cdnjs.cloudflare.com/ajax/libs/KaTeX/<?php echo $latestKatexCDNVers; ?>/katex.min.js

I'd run the version check script at a reasonable interval, say once per week, using cron.

But for me personally, I'd rather manually do this (apart from the fact KaTeX might change the way they number versions down the track and the above would break). That is, when a new version comes out, I want to test it thoroughly on my local system before deploying it. I then only have to change to the new version number in one place (because of the way I've set up my calls to JS). 

Regards

**Comment by edemaine** [comment]
According to https://github.com/cdnjs/cdnjs/issues/987 it's not possible with CDNJS.  And indeed, it's no longer possible with MathJax; see [this retirement notice](https://www.mathjax.org/cdn-shutting-down/), which uses explicit version numbers.  So, alas, I don't think there's a way to support the requested feature, except workarounds like @mbourne's.  Closing this unless there are other ideas.
