### ISSUE TITLE
Use MathJax jax for input parsing?

### ISSUE THREAD

**Issue by csilvers** [Khan/KaTeX#730]
This is just an idea, and maybe one that is unworkable on its face, but I thought it would be interesting and productive to discuss: why not have katex use MathJax's parser to generate an internal representation of the math, rather than having our own parser?  Another way to think of it, why not have katex just be an "output jax" for MathJax?  (Though in practice we'd probably want to bundle katex and the mathjax input processing into its own package as well, to not have to pay some mathjax flexibility overhead.)

According to http://docs.mathjax.org/en/latest/advanced/model.html, MathJax is separated into "input jax"es, which process tex (and other input formats) into something looking like mathml, and "output jax"es which convert that into different formats.

This seems relevant to PR #251, which wants an internal representation to map to canvas.

It's possible that the mathjax parser is just too slow for katex's purposes, or that generating html+css from that internal representation is too slow; I don't know why mathjax is as slow as it is.  But I think it would be interesting to think about.

(There's no real actionable item here necessarily; I'm making this an issue since I don't know other wys to have discussions on github.)

**Comment by edemaine** [comment]
It's an interesting idea, which would probably need some experimentation before we could really evaluate whether it's a "good" idea performance-wise.  In particular, how much of MathJax's slowness is from parsing vs. from rendering?  This should be easy enough to measure.  [This mathjax performance wiki page](https://github.com/mathjax/MathJax/wiki/Understanding-mathjax-performance) claims that rendering is especially painful because they do lots of round-trips to the browser to measure actual widths and heights (hey, it's like our horizontal metrics discussion!).  But that's apparently not necessary for their SVG rendering, yet their SVG running times are still pretty slow.  So I worry that their parse is slow relative to KaTeX's.

Aside from performance, this would be a huge rewrite of KaTeX, I imagine, given how intertwined the parser and the renderers are currently.  Might be a different project altogether...

**Comment by kevinbarabash** [comment]
> But that's apparently not necessary for their SVG rendering, yet their SVG running times are still pretty slow.

The last time I looked into MathJax's SVG rendering it looked like they created an offscreen SVG element that contained all of the glyphs that they needed to render for any on-screen math.  I assumed that it was measuring the glyphs in this off-screen canvas to figure out their metrics.

> why not have katex use MathJax's parser to generate an internal representation of the math, rather than having our own parser? Another way to think of it, why not have katex just be an "output jax" for MathJax?

One way to approach this would be to write a converter that takes intermediate "jax" representation and transforms it KaTeX's current parse tree.  That should mean minimal changes to existing KaTeX code.

**Comment by kevinbarabash** [comment]
The "jax" format seems pretty straight forward, here's the tree for `ax^2 + bx + c = 0` partially expanded.
<img width="743" alt="screen shot 2017-07-16 at 7 07 34 pm" src="https://user-images.githubusercontent.com/1044413/28253582-2fbc8608-6a5a-11e7-8549-c92e22656551.png">

**Comment by kevinbarabash** [comment]
If you squint hard enough at it, it looks like MathML with some extra props.

**Comment by kevinbarabash** [comment]
Here's what KaTeX's parse tree looks like for the same expression:
```
[Log] [ (katex.js, line 40)
    {
        "type": "mathord",
        "value": "a",
        "mode": "math"
    },
    {
        "type": "supsub",
        "value": {
            "base": {
                "type": "mathord",
                "value": "x",
                "mode": "math"
            },
            "sup": {
                "type": "textord",
                "value": "2",
                "mode": "math"
            }
        },
        "mode": "math"
    },
    {
        "type": "bin",
        "value": "+",
        "mode": "math"
    },
    {
        "type": "mathord",
        "value": "b",
        "mode": "math"
    },
    {
        "type": "mathord",
        "value": "x",
        "mode": "math"
    },
    {
        "type": "bin",
        "value": "+",
        "mode": "math"
    },
    {
        "type": "mathord",
        "value": "c",
        "mode": "math"
    },
    {
        "type": "rel",
        "value": "=",
        "mode": "math"
    },
    {
        "type": "textord",
        "value": "0",
        "mode": "math"
    }
]
```

The `supsub` is of particular interest so let's zoom in:
```
    {
        "type": "supsub",
        "value": {
            "base": {
                "type": "mathord",
                "value": "x",
                "mode": "math"
            },
            "sup": {
                "type": "textord",
                "value": "2",
                "mode": "math"
            }
        },
        "mode": "math"
    },
```
<img width="882" alt="screen shot 2017-07-16 at 7 29 03 pm" src="https://user-images.githubusercontent.com/1044413/28253939-36ad607e-6a5d-11e7-8909-7b71ccc74797.png">

MathJax stores a number of properties on the prototype.  My guess is this was done so that it's easier to walk the tree.  The downside of this (along with the `parent`  property) is that these data structures aren't serializable.  If we're looking for a shared data format which could be used in #251, I'd avoid MathJax's internal format for this reason.  The KaTeX structure isn't bad, but it could be made more regular as currently `value` props can be an `object` of various shapes or a `string`.

**Comment by kevinbarabash** [comment]
I'm going to close this for now.  We may revisit this depending on what MathJax does for parsing in their v3 rewrite.
