### ISSUE TITLE
using \color colors more than it should

### ISSUE THREAD

**Issue by jonnydman** [Khan/KaTeX#838]
if I try to use the next example:

`\color{blue}{'helllo there'}+123`

the '+123' also gets the blue color

**Comment by kevinbarabash** [comment]
quick latex.com renders it as:
<img width="357" alt="screen shot 2017-09-02 at 8 28 28 pm" src="https://user-images.githubusercontent.com/1044413/29999611-4ed45af0-901d-11e7-9f7f-e069e05fa271.png">
so I believe we're doing the right thing.

If you want only `'hello there'` to be color you'll have to do: `{\color{blue}'hello there'}+123`.  There was a breaking change in behavior recently with the [v0.8.0](https://github.com/Khan/KaTeX/releases/tag/v0.8.0) release so that our behavior would align with what LaTeX does (as opposed to MathJax).

**Comment by ronkok** [comment]
There is an explanation [here](https://khan.github.io/KaTeX/function-support.html#color).

**Comment by jonnydman** [comment]
Thanks!
