### ISSUE TITLE
move handlers for implicit group functions out of Parser.js

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#868]
This will allow `defineFunction` to be more regular and will allow us to consolidate code for the parsing and building of HTML/MathML for these functions in a single place.  This affects sizing, style changing, old font changing, and color changing functions as well as `\left`/`\right` delimiters.  Most should be relatively straight forward except for the delimiters which will probably require the handler to modify the parser's `leftrightDepth` state.

**Comment by edemaine** [comment]
Long ago @gagern pointed out that these could probably mostly go into `functions`, because functions now have access to the parser (I'm guessing they didn't before).  Alternatively, we could extend the argument handling to support another option "implicit".  Haven't looked at this carefully, but this approach is one option for achieving this goal.

**Comment by ylemkimon** [comment]
Closing as most of handlers are moved to `functions/`.
