### ISSUE TITLE
{aligned} kills last line if first column is empty

### ISSUE THREAD

**Issue by ccorn** [Khan/KaTeX#946]
Rendering
~~~ latex
\begin{aligned}&E_1 & (1)\\&E_2 & (2)\\&E_3 & (3)\end{aligned}
~~~
with release 0.9.0-alpha1 kills the last line of output. 0.8.3 leaves it intact.
Appending `\\` to the last line adds it back in.
Sorry for not contributing a dedicated test suite entry, my platform does not support Node.js. Found when testing `katex.renderToString` with Duktape.
Might have to do with #337.

**Comment by ronkok** [comment]
I can confirm that in @ccorn's test case, KaTeX master does indeed eat the last line. And it doesn't matter if the first two rows have their first column empty or not. It's just the last row of the environment that matters here.

I believe the issue is related to PR #337. If I remove those lines of code, the behavior reverts to release 0.8.3.

**Comment by ronkok** [comment]
The variable `lastRow` doesn't seem to be picking up a whole row. It seems to pick up one cell.

Perhaps those lines could be revised to:
````
            const lastRow = body[body.length - 1];
            if (body.length > 1
                && lastRow.length === 1
                && lastRow[0].value.length === 0) {
                body.pop();
            }
````
