### ISSUE TITLE
Division line of \frac not rendered in Chrome in special case

### ISSUE THREAD

**Issue by bergwerf** [Khan/KaTeX#962]
Rendering `\left(\frac{a}{b_a}\right)` using https://khan.github.io/KaTeX/ gives the following at 100% and 80% zoom.

![image](https://user-images.githubusercontent.com/4458965/32701207-80a5da0e-c7d1-11e7-99ba-84609f7b3910.png)

 Other zoom levels are unaffected. This might also be a bug in Chrome but I could not quite figure it out.

**Comment by edemaine** [comment]
The latest alpha1 release should have already fixed this. We're not yet using it on github.io.

**Comment by bergwerf** [comment]
I just tested from the master branch and there at least the issue seems to be resolved (I imagine this to be quite tricky, maybe dependent on font settings and such, all I did was make && make serve and removing the font-size: 7*px from the demo page). Out of curiosity, what was causing this issue?

**Comment by edemaine** [comment]
It seems that Chrome (*only*) rounds *down* fractional line widths to zero (maybe only when they're less than 1/2, or some other circumstance).  I'm not sure whether this is against the standard, but it's definitely annoying for our case.  PR #931 used some CSS magic to guarantee that the line width doesn't go below 1 *screen* pixel (different from 1px).  It also links to issues where this problem was discussed more.
